package nl.jiankai.year2024;


import java.util.*;

public class Day12 {
    public static void main(String[] args) {
        part2();
    }

    public static void part1() {
        String[][] grid = Arrays.stream(input.split("\n")).map(s -> s.split("")).toArray(String[][]::new);
        Set<Pos> visited = new HashSet<>();
        List<Set<Plant>> groups = new ArrayList<>();

        for (int y = 0; y < grid.length; y++) {
            for (int x = 0; x < grid[y].length; x++) {
                Set<Plant> group = new HashSet<>();
                area(group, visited, grid, x, y, grid[y][x]);
                if (!group.isEmpty()) {
                    groups.add(group);
                }
            }
        }
        int ans = 0;

        for (Set<Plant> group : groups) {
            int perimeter = 0;
            for (Plant plant : group) {
                if (!group.contains(new Plant(plant.x - 1, plant.y, plant.c))) {
                    perimeter += 1;
                }

                if (!group.contains(new Plant(plant.x + 1, plant.y, plant.c))) {
                    perimeter += 1;
                }

                if (!group.contains(new Plant(plant.x, plant.y + 1, plant.c))) {
                    perimeter += 1;
                }

                if (!group.contains(new Plant(plant.x, plant.y - 1, plant.c))) {
                    perimeter += 1;
                }
            }
            ans += perimeter * group.size();
        }

        System.out.println(ans);
    }

    public static void part2() {
        String[][] grid = Arrays.stream(input.split("\n")).map(s -> s.split("")).toArray(String[][]::new);
        Set<Pos> visited = new HashSet<>();
        List<Set<Plant>> groups = new ArrayList<>();

        for (int y = 0; y < grid.length; y++) {
            for (int x = 0; x < grid[y].length; x++) {
                Set<Plant> group = new HashSet<>();
                area(group, visited, grid, x, y, grid[y][x]);
                if (!group.isEmpty()) {
                    groups.add(group);
                }
            }
        }
        int ans = 0;

        for (Set<Plant> group : groups) {
            int sides = 0;
            Map<Side, List<Integer>> xSide = new HashMap<>();
            Map<Side, List<Integer>> ySide = new HashMap<>();
            for (Plant plant : group) {
                if (!group.contains(new Plant(plant.x - 1, plant.y, plant.c))) {
                    xSide.computeIfAbsent(new Side(plant.x, true), x -> new ArrayList<>()).add(plant.y);
                }

                if (!group.contains(new Plant(plant.x + 1, plant.y, plant.c))) {
                    xSide.computeIfAbsent(new Side(plant.x, false), x -> new ArrayList<>()).add(plant.y);

                }

                if (!group.contains(new Plant(plant.x, plant.y - 1, plant.c))) {
                    ySide.computeIfAbsent(new Side(plant.y, true), x -> new ArrayList<>()).add(plant.x);

                }

                if (!group.contains(new Plant(plant.x, plant.y + 1, plant.c))) {
                    ySide.computeIfAbsent(new Side(plant.y, false), x -> new ArrayList<>()).add(plant.x);
                }
            }

            for (Map.Entry<Side, List<Integer>> entry : xSide.entrySet()) {
                List<Integer> list = entry.getValue();
                Collections.sort(list);
                for (int i = 1;  i < list.size(); i++) {
                    if (Math.abs(list.get(i) - list.get(i-1)) >= 2) {
                        sides++;
                    }
                }
            }

            for (Map.Entry<Side, List<Integer>> entry : ySide.entrySet()) {
                List<Integer> list = entry.getValue();
                Collections.sort(list);
                for (int i = 1;  i < list.size(); i++) {
                    if (Math.abs(list.get(i) - list.get(i-1)) >= 2) {
                        sides++;
                    }
                }
            }
            sides += xSide.size() + ySide.size();
            ans += group.size() * sides;
        }

        System.out.println(ans);
    }


    private record Side(int val, boolean other) {
    }

    private static void area(Set<Plant> plants, Set<Pos> visited, String[][] grid, int x, int y, String c) {
        if (x < 0 || y < 0 || x >= grid.length || y >= grid[0].length) {
            return;
        }

        if (visited.contains(new Pos(x, y))) {
            return;
        }


        if (grid[y][x].equals(c)) {
            visited.add(new Pos(x, y));
            plants.add(new Plant(x, y, c));
            area(plants, visited, grid, x - 1, y, c);
            area(plants, visited, grid, x + 1, y, c);
            area(plants, visited, grid, x, y - 1, c);
            area(plants, visited, grid, x, y + 1, c);
        }
    }


    private record Pos(int x, int y) {
    }

    private record Plant(int x, int y, String c) {
    }

    private static final String input = """
YYYYYMMMMMMUUUUUUUUNNNNUTTTTTAASAXXXXXHHEEHHEEEEERYYYYYYYYYYHHHHHHHHHHHHHHHHFFFFFFFFFFAAAAAAAAAAAAAOOOOOOOOYYYYYYYYYYYYYYYYVVVVWWWWWWWZZZZZZ
YYYYYMMMMMMUMUUUUUUUUUUUTTAAALAAAAXXXHHFHHHEEEEEERRRRYYYYYYQHHHHHHHHHHHHHHHHHFFFFFFFFFAAAAAAMMMMMMMMMMMOOOOOYYYYYYYYYYYYYYYVVVWWWWWWKWZZZZZZ
YYYYYMMMMMMMMMMUUUUUUUUUTAAAAAAAAXXXXHHHHHHEEEEEERRRYYRYYYYQQHHHHHHHHHHHHHHHHFFFFFFAAAAAAAAAMMMMFMMMMOOOOOOOYYYYYYYYYYYYYYVVVVWWWTWKKWZKKZZZ
YYYYYYMMMMMMMUUUUUUUUUUUUAAAAAAAAHHHHHHHHHHHEEERRRRRYYRQQQQQQHHHHHHHHHHHHHHHHFFFFFAAAAAAAAAAAMMMMMMMMOOOOOOOYYYYYYYYYYYNDDDDDDTTTTTKKKKKKZZZ
YYYYMMMMMMMMMUUUUUUUUUUUUAAAAAAAAHHHHHHHHHHHMEERRRRRRRRRQQQQQQQHHHHHHHHHHHHHFFFFFFAAAAAAAAAAAMMMMMMMMOOOOOOOOYYYYYYYYYYNDDDDDDDDTTKKKKKKKKKK
YYYMMMMMMMMMMMMUUUUUUUUUUAAAAAAAAHHHHHHHHHKHMEERRRRRRRRQQQQQQQQQHHHHHHHHHHHHHFFFFFFFAAAAAAMMMMMMMMMMMOOOOOOOYYKYYYYYYYYNNDDDDDDTTKKKKKKKKKKM
YYYYMMMMMMMMMMMUUUUUUAUUUAAAAAAAHHHHHHHHMMMMMEERRIRRRQQQQQQQQQQQIHHHHHHHHHHHHHFFTTTFAVVAUUUUMMMMMMMMMMOOOOOOOYYYYYCYYDDDDDDDDDDTTTTTKKKKKKKM
YYYMMMMMMMMMMMMMUPPUUAAAAAAAAAAAAHHYYLQQMMMMMEEIIIRRRRQQQQQQQQQQHHHHHHHHHHLLHFFTTTTTRRVVVVUUMMMMMMMMMMMOOOOOOYYYYYFFVVDDDDDDDDDKKKKKKKKKKKKK
YYYMMMMMMMMMMMMMUPPPAAAAAAAAAABBAHHHHLQLLMLLMEIIIIIIRRQQQQQQQQQQQXHHHHHHHHKLHFFTTTTTRRVVVVVUMMMMMMMMPOOOOOOOYYYFYFFFFFFDDDDDDDDDKKKKKKKKKKKK
YYYYMMMMMMMMMMOOUPPPPPNNAAAAABBOHHHHHLLLLLLLLIIIIIINIRRQQQQQQQQQQXHHHHHHHHKKHFFOOTTVVVVVVVVMMMMMMMMMPOOOOOOOOOFFFFFFFFFDDDDDDDDDWWKKKKKKKKKK
YYYYYMMMMMMMMMMUUPPPPNNNAAABBBBOHHHHLLLLLLLLIIIIIIIIIRQQQQQQQQQQQXXHHHHHHHKKHFFKOTTVVVVVVVVVOMMMMMZMPOOOOOOOOOFFFFFFFFFFDDDDDDDDDWWKKKKKKKKK
YEEMMMMMMMZMMMRRRPPNNNNNNAABBBBOOHHLLLLLLLLLLLIIIAIIIRRRQRQQQQQQQQXXHHHKCHKKKKKKOOOVVVVVVVVVVSMMMMMSOOOOOOOOOOFFFFFFFFFDDDDDDDDDWKKKKKKKKKKK
EYEEMMMMMMMMMMRNNPNNNNNNAAAABBBOOLLLLLLLLLLLLIIIIIIIRRRRRRRRQQSQCSXXXXXKKKKKKKKKOOOVVVVVVSVVVSMMMMSSSOOOOOOOOOFFFFFFFFFFDDDDDDDDWKKKKKKKKWKK
EEEEEQMMMMMGMRRTNNNNNNNNAAAAPAJAALLLLLLLLLLLLIIIIIIIRRRRRRRRQSSSSSSXXKKKKKKKKKKKKVVVVVVVRSVVSSMMSSSSSOOOOOOOCCFFFFFFFFFFDDDDDDDDWWKWWWWWKWWW
EEEEEEEMNNMGTTTTTNNNNNNNAAAAAAAAALLLLLLLLLLLLIIIIIIIIRRRRRRRRSSSSSSXXKKKKKKKKKZZVVVVVVVVRSSSSSSSSSSSLOOOOLLOOLZFFFFFFFFFFFFDDDDDWWWWWWWWWWWW
EEEEEEEMMEGGTTTTNNNNNNNWNAAAAAAJALLLLLLLLLLLIIIIIIIIBZZZZRRRSSSSSSSSSKKKKKKKKKZZZVVVVVRRRRRSSSSSSSLLLOLLLLLLLLPFFFFFFPFPFFDDDDDDDWWWWWWWWWWW
EEEEEEEEEEEEVTTTNNNNNNNNNAAAAAAAPLLLWLLWWLLLLIIIIIIIBZZZZRRSSSSSSSSSAKKKKKKKKKZZZZVVVRRRRRRSSSSSSLLLLLLLLLLLLPPFFFFPPPPPFDDDDDDDDVWWWWWWWWWW
EEEEEEEEEEEEETTTTTNNNNNNNAAAAAPPPPPLWWWWWLLLLLLZIIIBBBZZZZRSSSSSSSSSSKKKKKKKZZZZZZZVVRRVRRRRSSTSSLSLLLLLLLLLLLPPPPPPPPPPPDDDDDDDVVWWWWWWWWWW
EEEEEEEEEEEEEEETTTNNNNNNNAAAAPPPPPPPPWWTWLLLLLLZZIIBBBZZZRRRSSSSSSWSKKKKKZZKZZZZZZZZZTRRRRRRTSTTSSSNNLLLLLLLLPPPPPBPPPPVDDDDDDDDDVVVWWWWWWWW
EEEEENEEEEEEEEETTNNNNNNNNAAAAPPPPPPPPWAWWLLWLLZZZZIZZZZZZZRRSSSSSSSHHKKKKKZZZZZZZZZZZTTRRRRRTTTSSSSNNNNLLLLLLPPPPPPPPPBVVVDDDDDVVVVVWWWWWWWW
EEEENNNEEEEEEEENNNNNNNNNNAGGDGGGGPPPPWWWWWWWLLZZZZZZZZZZZZRRSSSSSSSHHKKKKKQZZZZZZZZZZTTTTRRTTTTTSSSNNNNLLLLLLLLPPPPPPPVVVVVDDVDVVVVVWWWWWWWW
EEEENNNNNNEEPPEPNNNNNNNMGGGGDDGGGGPPPWWWWWWWWWZZZZZZZZZZZZRRSSSSSSSHKKKKNNNPPZZZZZZZTTTTRRRTTTNNSNSNNNNLNLLLLLLPPPPPPPPVVVVVVVVVVVVWWWWWWWWW
EEEENNNNNNNNPPPPNNNNNNNMGGGGGGGGGWWPPPWWWWWWWZZZZZZZZZZZZZZRRRSSSSSHHHHHHNNNZZZZZZZZTTTTTTTTNNNNNNNNNNNNNNLLLLPPPPPPEPEVVVVVVVVVVVVVWWWWWWWW
EEENNNNNHNNNPNNNNNNNNNNNNGGWGGGGGGWWWWWWWWWWWZZZZZZZZZZZZZZRSSSSSSSSHHHHHNNNNNZZZZZTTTTTTTTTTNNNNNNNNNNNNNLLLLPPPPPPEPEEEVVEVVVVVVVVWWWWWUUW
ENNNNNNNNNNNNNJJNVVVVVNENGGGGGGGGGWWWWWWWWWSSRZRZZZZZZZZZZZZSSSSSSSHHHHQHHNNNZZZTTTTTTTTTTTTTNNNNNNNNNNNNNNNNLPPPPPPEEEEEEEEEEVVVVVWWVWWWUWW
NDNNNNNNNNNNNNGGGVVVVNNVVGGGGGGGGGWWWWWWWWWWSRRRZZZZZZZZZZZZZSSSSSQHHHQQQQNNNNZTTTTTTTTTTTTTNNNNNNNNNNNNNNNNLLLLPPEEEEEEEEEEEEVVVVVVVVWWWUUU
NNNNNNNNNNNNGGGGGGVVVVVVGGGGSGBBGGGWWWWWWWRRRRRNNNZZZZZZZZZZZQQQSQQQHQQQQNNNNNTTTTTTTTTTTTNTNNNNNNNNNNNNNKLLLLLLPPEKEEEEEEEEEEEEVVVVVWWWWWWU
NNNNNNNNNNNNGGGGGGGGVVVVGGGGBBBBGGGGGWWWWVRRRRRRRNZZZZZZZZZZZQQQSQQQQQQQQNNNNNTTTTTTTTTTTTNNNNNNNNNNNNNNNKLLLLLKKKKKEEEEEEEEEEEEVVVVVWWWWWUU
NNNNNNNNNNNNNGGGGGGGVVVGGBBBBBBBGGGGGGWWWRRRRRRRRRZZZZZZZZZZZQQQQQQQQQQQNNNNNNNTTTTTTTTTTTYNNNNNNNNNNNNYYKKKLLLKKKKKKKEEEEEEMMMMVVVMWWWWWWUW
NNNNNNNNNNNNNZGGGGGVVVGGGGGGGGBGGGGGGOOWXRRRRRRRRRLZWWHZKZRZQQQQQQQQQQQQNNOOONTTTOBBTTTTTTTBBBNNNNNNNNNYYYKKKKKKKKKKKKEKEFEMMMMMZMMMWWWWWWUW
NNNNNNNNNNNNZZZZZJJJJGGGGGGGGGGGGGGGGOOOXRRRRRRRRRRWWWWWWRRZQQQQQQQQQQQQQNNOONMTOOBBBTTCTCTBBBNNNNNNYYNYYYYYKKKFKFFKKKEKEMMMMSMMMMMMWWWWWWWW
NNNNNNNNNNNNNZJJJJJJJJGGGGZGGGGGGGGGGGOOOORRRRRRRRWWWWWWWRWMWQQQQQQQQQPNNNOOOOOOOOOBTTTCCCBBBBNINNNNNYNYYYYYYFFFFFFFAKEKKMMMMMMMMMMWWWWWTTWW
NNNCCNNNNNNNNNNJJJJJJJGGGZZZGGGGGGGGGGGOOLLTTRRRRRWWWWWWWWWWWWQQQQQQQQQQQOOOOOOOOOOBBBTTCCBBBBBNNTNNYYYYYYYYYFFFFFFAAAKKMMMMMMMMMMMWWWWWWTTW
CCCCCNNNNNNNNJJJJJJJJCZZZZZZZGGGGGGGGGGOOLLTTRRRRRWWWWWWWWWQQQQQQQQQQQQQDDOOOOOOBOBBBBBBBBBBBBBYTTNYYYYYYYYYYFFFAALAAAAAMMMMMMMMMMMMWWWWWWTW
CCCCCIINNNNNJJJJJJJJJJZZZZZZZGGGGGGGGGGGGTTTRRRRRWWWWWWWWWWQQQQQQQQQQQQQDDOOOOOOBBBBBBBBBBBBBBBYYYYYYYYYYYYYFFFFFAAAAAAAMMMMMMMMMMMMMWWWWWWW
CCCCCCCCNNNKKKKJJJJJZZZZZZZZGGGGGGGGGGYTTTTTTRRWRWWWWWWKKZQQQQQQQHQZZTQQQOOOOOOOOBBBBBBBBBBBBBBYYYYYYYYYYYYYFFFFAAAAAAAAMMMMMMMMMMMMMWWWWWWW
CCCCCCCCCNNNKJJJJJJZZZZZZZZZZGGGGGGJGTTTTTTTTRWWWWWWWWKKKKQQQQQQQQQQZZQZZOZOOOOOOBBBBBBBBBBBBKKYYYYYYYYYYYYWWFFFAAAAAAMMMMMMMMVVVMMMMWWWWWWW
CCCCCCCCCNNNKMJJJJJZZZZZZWWWNWWKGGOJOTTTTTTTBRWWWWWWWWKKKKQQQQQQQQVZZZZZZZZOOOBBOBBBBBBBBKKBKKKKYYYYYYYYYYWWWFWFAAAAAAAMMMVVVVVVVVMMWWWWWWWW
CCCCCCCCCCNNJJJJJJJZZZZZZZWWWWWWWGOOOOTTTTTTTWWWWWWWWKKKKKQQQQTQQQVVVVZZZZZMGBBBBBBBBBBBBBKKKKKYYYYYYYYYYWWWWWWWAAAAAAAMMMMVVVVVVVWWWWPPPPPW
CCCCCCCCCNNNNJJJJJJZZZZZZZZWWZZZWOOOOTTTTTTTWWWWWWWWWKKKKEEEZZZZZZZVVVZZZZZGGBBBBBBBBBBKKKKKKKLLLYYYYYYYYGWWWWWWWWWWAAMMMMMMVVVVWWWWWWPDPPPW
CCCCCCCCCCNFNFJJJZJJZZZZZZZWWZZBBBBOQQQTTTTTTWWWWWWWWKKKKKEGGZZZZZZZZZZZZZZGGGGGBBBBBKKKKKKKKKKLLYYYYYYYYGWWWWWWWWWWWWPMMMVVVVVVWWWPPPPPPPPP
CCCCCCCCCCNFNFFZZZZZZZZZZZWWWZZBBBBBBBBBBTTRWWWWWWWWWWKKEEEGGGRZHHZZZZZZZZGGGGGBBBBBKKKKKKKKKKKKKYYYYYYYYWWWWWWWWWWWWWPPPPVVVVVVWWWPPPPPPPPP
CCCCCCCCCCCFFFFFFZZZZZZZZZZZZZZBBBBBBBBBBTRRRRRRWWWWWWWWEEGGGGRRRHZZZZZZZZGGGGGGBBBEEEGKKKKKKKKKKYYYYYYYWWWWWWWWWWWWWWWPPPPDDVDWWWPPPPPPPPPP
CCCCCCCCCCCFFFFFFFZZZZZZZZZZZZWBBBBBBBBBBQRRRRRRWRRRWWWWWEEGGGGRHHHZZZZZGGGGGGGGBBEEEEEKKKKKKKKKKKYKMJYYLWWWWWWWWWWWWWWWWWDDDDDWWWPPPPPPPPPP
CCCCCCCCCCCCXPFFFFFZZZZZZZZZZZWBBBBBBBBBBQRRRRRRRRRRWRWWWEWRRRRRHHZZZZZZGGGGGGGGGBEEEEEEEEEKKKKKKKYKMMMLLLLWWWWWWTWWDDDDDDDDDDWWWWPPPPPPPPPP
CCCCCCCCCCCCPPPPFFFZZZZZZZZZZZBBBBBBBBBORRRRRRRRRRRRRRWWWWWWRRRHHHHHHHZZGGGGGGGGGGEEEEEEEEKKKKKKKKKKMMMMMLLLLWWWTTWTTTDDDDDDDDDDDWPPPPRRPPPC
CCCCCCCCCCCPPPPPFFFFZZZZZZZZZZBBBBBBBBBOLLRRRRRRRRRRRRWWWWWRRRHHHHHHHHHGGGGGGGGGGGEEEEEEEEEKKKKKKMMMMMMMMMMLLLWWTTTTTTTTDDDDDDDDDDPPPPPRPPPP
CCCCCCCCCCCCPPPAFPLFZZZZZZZZZZBBBBBLLLLLLLRRRRRRRRRRRRWRWRRRRRHHHHHHHHHHGGGGGGGBBBGEEEEEEEEEKKKKMMMMMMMMMMMLNNNNTTTTTTTDDDDDDDDDCCCPPPPRRRPR
CCCCCCCCCCPPPPPPPPBBZZZZZZZZBBBBBBBLLLLLLLLYYRRRRRRRRRRRRRRRRHHHHHHHHHHHGGGGGGGBBBGGGEEEEKKKKKKKMMMMMMMMMMMLLNNNNTTTTDDDDDDDDDDCCCCPPRRRRRPR
CCCCCCCCCCCPPPPPPPBBBBBBBBDWBBBBBBBLLLLLLLLLRRRRRRRRRRRURRRRHHHHHHHHHHHBBBBBBBBBBBGGGEEEEEKKKKKMMMMMMMMMMMMLLNNNTTTTTTTDDDDDDDCCCRRRRRRRRRRR
CCCCCCCCCCPPPPPPPBBBBBBBDDDWBBBBBBBLLLLLLLLLRBRRARLLLLRUURRRHWHHHHHHHHGBBBBBBBBBBGGQGEEEEEEKKKKMMMMMMMMMMMMMLNNNTTTTTTTTTDDDDDDWRRRRRRRRRRRR
CCCCCCCCCCPPPPPPPBBBBBBDDDDDBBBBBBBBBBOLLLLLBBRRRLLLLLRUUUURRHHHHHHHHHHBBBBBBBBBBGGGGEEEEKKKKKMMMMMMMMMMMNNNNNNNNNNNTTTTWDDDDDWWRRRRRRRRRRRR
CCBBBBCCCCPPPPPPPBBBBBBBBDDDBBBBBBBBBBLLLLLLBBRRLLLLLLRUUUUURHHHHHHHHHHBBBBBBBBBBAAAAEEEEKKKKKKKMMMMMMMMMNNNNNNNNNNNTWWWWWWWDWWWWRRRRRRRRRRR
RRBRRBCBBCPPPPPPPBBBBBMMDDDDBBBBBBBBBBBLLLLLBBBRBLLLJJJUUUUUUEHHHHHHQQHBBBBBBBBBBAAAAEEEKKKKHHHHHHHHMMMMMNNNNNNNNNNNTWXWWWWWWWWWWWHRRRRRRRRR
RRRRRBBBBBBBJPPBBBBBBBBBBDDDBBBBBBBBBBBLLLLLLBBBBBBLJJJBUUUUUEEHHHHQRQQQBBBBQQAAPAAAAEEAKKKKHHHHHHHHMZMMMNNNNNNNNNNNNWXWWWWWWWWWWWHRRRRRRRRR
RRRBBBBBBBBJJPPBBBBBBBBBBBDDIIIIIIIIBBBLLLYLTTBBBBBLJJBBBUUUUEEHHHHQQQQQBBBBQQAAAAAAYEAAAKKKHHHHHHHHMZNNNNNNNNNNNNNXXXXWWZZZWWWJWWRRRRRRRRRR
RRRBBRBBBIJJIBBBBBBBBBBBBBIIIIIIIIIIBBBLLLLLTTBBBBBLBJBBBBUBBHHHHHHHQQQQBBBBAAAAAAAAAAAPYKKKHHHHHHHHMZZZNNNNNNNNNNNNNXXXXZZBZZJJWWRRRRRRRRRR
SSSSSSXBBIJIIIIBBBBBBBBBPIIIIIIIIILLLLLLLLLTTTBBBBBLBBBBBBBBBHHHHHHHQQQQBBBBAAAAAAAAAEEEEKKKYZZHHHHZZZZZZNNNNNNNNNNNXXXXZZZZZZJJJJJARRRRRRRR
SLSSSSSIIIIIIIIBBBBBBBBIIIIIIIIIIIIILLLLLLLLTBBBBBBBBPBBBBBBHHHHHHQQQQQQQQQQAAAAAAAAAEEEEYKKYYYHHHHZZZZZZNNNNNNNNNXXXXXXZZZZZZZJJJJAAARRRRRR
SSSSRSSIIIIIIIBBBBBBBBBBIIIIIIIIIIIELLLLLLTTTTBBBBPPPPPBIIBBBHHHHHHQQQQQQQQQQAAAAAAAAEEEEYYKYRRHHHHZZZZZZNNNNNNNNNNXXXZZZZZZZZJJJAAAAAARRRRR
SSSSSSSPIIIIIIIIBBBBBBBKIIIIIIIIIIILLLLLLLTTTBBIIPPPPPIIIBBBBBHHHHHQQQQQQQQQQAAAAAAAAEEEEYYYYRRHHHHZZZZZZZNNNOONTTNNZXZZZZZZZJJJAAAAAAARRRRR
SSSSSSPPPIIIIIIIIBBEBBBIIIIIIIIIIIILLLLLLLWTIOOIIIIIPIIIIBBBBHHHHHHQQQQQQQQQQQQAAAAAAEEEEYYYYRRRVVVZZZZZZZZNNNNNTTTZZXZZZZZZZZZZAAAAAAARRRRR
SSSSSSIIIIIIIIIIIIEEBBQQIIIIIIIIIIIILLLLLLLLOOOIIIIIPIIIIBHBHHHHHHHHHQQQQQQQFQQAAAAAAEEEEYYYYYRRRVVVZVZZZZQCQQTTTTTTZZZZZZZZZAAAAAAAAAAAKRRR
SSSSSSIIIIIIIIIIIIIIIIQQIIIIIIIIIILLLLLLLLLLROOOIIIIIIIIIHHHHHHHHHHHHQQQQQQQFFFBAAAAAEEEEYYRRRRRRVVVVVVVVQQQQQQTTTTTZZZZZZZZZOAAAAAAAAAAKRRF
SSSSIIIIIIIIIIIIIIIIIIIQQIIIIIIIIILLLLLLLLLLOOOOOIIIIIFIIHHHHHHHDDDDQQQQQQQQQQFFQAEEEEEEEEEYRRRRRVVVVVVCVQQQQQLQTTTZZZZNZZZXAOAAAAAAAAAAAAAF
SSIIIIIIIIIIIIIIIYYIJIIQQIIIIIIIIILLLLLLLLLLIIIIIIIIIIIJIHHHHHHHDDDDDQKQQQQQQQQFQAEEEEEEEEEYRRVVVVVVVVVCCQQQQQQQTTTTZZZNNNTTAAAAAAAAAAAAAAAF
SSISSSIIIIIIIIHIIYIIHQQQQQIAAIIIIILLLLLLLLLLLIIIIIIIIIJJJJHHHHHHDDDDQQKQAQQQQQQQQAEEEEEEEEEYVVVVVVVVVVVVVVQQQQQQTTTTBBNNNTTTTAAAAAAAAAAAAAAF
SSSSSSIIIIIIIHHHHHHHHHQQQAAAAIIAIALLLLLLHLLLIIIIIIIJJJJJHHHHHHHPDDDDDDDQQQSQQQQQQQEEEEEEEEEYYVVVVVVVVVVVFQQQQQQQQQTBBITNTTTTTTTTAAAAAAAAAAAF
SSSSSSIIIHHIHHHHHHHHHHQQQQAAAAAAAAALHHHHHHHIIIIIEEJJJJJJJHHPPPPPDDDDDDDDSSSQQQQQQQEEEEEEEEEYVVVVVVVVVVVVQQQQQQQQQQQBBTTTTTTTTTTTTAAAAAAAABBB
SSSSSSIIIHHHHHHHHHHHHHQAAAAAAAAAAAAHHHHHHHIIEEIEEJJJJJJJJEEPPPDDDDDDDDBYYSSQQQQQQQAYYDYYYYYYVVVRVVVVVVVVQQQQQQQQQQKBBOTTTTTTTTTTAAAAAAABBBBB
RSSSSSSIIHHHHHHHHHHHHHQAAAAAAAHAAAAHHHHHHHHHHEEEEJJJJJJJEEEPDDDDDDDDDYBBYYQQQQQQQYYYYYYYYYYYYYVVVVVVVVVQQQQQQQQQQBBBBBZTTTTTTTTTTTAAAAABOBBB
RSSSSSSHHHHHHHHHHHHHHHQQQDAAAAHHHHHHHHHHEHEEEEEEEEJEJEEEEEEDDDDDDDDDDYYYYYSQQQQQQQYYYYYYYYYYYYVVVVVVVVVVQQQQQQQBHBBBBBBTTTTTTTTTTTHAAAAABBBB
RRRRRRVHHHHHHHHHHHHHHHHDDDAAAHHHHHHHHHHHEEEEEEEEEEJEEEEEDDDDDDDDDDDDDYYYIYSQQQQQQQQYYYYYYYYYYYVVVVVVVVVVVQQQQAAAAAAAAABBTTTTTTTTHHHAHAHBBBBB
RRRRRRVHVVHVHHHHHHHHFFHDDDAAADHHHHHHHHHHECEEEEEEEEEEEEEDDDDDDDDDDDDDDYLYYYSSSSSSQQQYYYYYYYYYYVVVVVVVVVVVVVQQQAAAAAAAAABWTVVTTTTTHHHHHHHHHBBB
RRRRRRVHVVVVVHHHHHHHFFFFDDDDDDHHHHHHHHHHECEEEEEEEEEEEEEDDDDDDDDDDDDDDLLLYQEESSSSSSSYYYYYYYYYYHVVVVVVVVVQQAAAAAAAAAAAAABSSSSTTTAHHHHHHHHHHBBB
RRRRVVVVVVVVVVHHHHHHHFFDDDDDDDDHHDHHHHHHHEEEEEEEEETTEETDDDDDDDDDDDDDLLLLLEEEESSSSSSSSYYYYYYYYHLVVVLVVPIQQAAAAAAAAAAAAASSSSQTSTNNHHHHHHHHHHHH
RRRRRVVVVVVVVVHHHHHHHFFDFDDDDDDDDDDHDHHHHHEEEEEEEETTTTTTTDDDDDDDDDDDLLZZZZEEEEEEESSSSYYYYYYXXLLLLLLIIIIIIAAAAAAAAAAAAASSSSSSSSNNNHHHHHHHHHHH
RRRRVVVVVVVVVVDHHHHHFFFFFIDDDDDDDDDDDNHHHHEEEEEEEETTTTTTTTDDDDDDDDDDDZZZZZZEEEEEESEESEGYNXXXXXLLLLLIIIIIIAAAAAAAAAAAAASSSSSSNNNNNHHHHHHHHHHH
RRRRVVVVVVVVVVVHHHHFFFFFIIDDDDDDDDDDDNNHHNQQEEEEEETTTTTTTZDDDDDDDDDDZZZZZZEEEEEEEEEEEEGXXXXXLLLLLLLLIIIIIAAAAAAAAQSSSSSSSSSSSSVHHHHHHHHHHHHH
RRRRVVVVVVVVVVVJOHJFJJJIIDDDDDDDDDDDDNNHNNNNIEEEEETTTTTTTDDDDDDDDDDDZZZZZZZZZEEEEEEEEEEEXXXXXXXLLLLLLIIAAAAAAAAAAQSSSSSSSSSSGSVHHHHHHHHHHHHH
RRRVVVVVVVVVVVVJOJJJJJJJIDDDDDDDDDDDNNNNNNNIIEYYEKTTTTTTTTDDDDNDNDZZZZZZZZZZEEEEEEEEEEXXXXXXXLLLLLIIIIIAAAAAAAAAAAAAZSSSSSSSSSSSVVVHHHHHHHHH
RKRRVVVVVVVVVVJJJJJJJJJIIIIIDDDDDDDDDNNNNNNIIINYYATNTBTTTTDDDDNNNNNZZZZZZZZZEEEEEEEEEXXXXXXQLLLLLLIIIIIAAAAAAAAAAAAASSSSSSSSSCVVVVVHHHHHHHHH
KKRRRVNVVVVVJJJJJJJJJJIIIIIIDDDDDDDDDNNNNNNNNNNYNAANABTTTTADDDNNNNNNZZZZZZZZEEEEEEEEXXXXXXQQQLLQLQIIIIIAAAAAAAAAAAAAASSSSSSSSVVVVVHHHHHHHHHH
KKKKRNNVVVVVJJJJJJJJJIIIIIIDDDDRDDDDNNNNNNNNNNNNNAAAAATTAAAADDNNNNNNZZZZZZZEEEEEEEEXXXXXXXQQQOJJJJJJQIIAAAAAAAAAAAAAASSSSSSSSVVVVVVVVVVHHHHH
WKKKWNVVVVVFJJJJJJJJJIIIIIIDDDDRRDNNNNNNNNNNNNUUUAAAAAAAAAAAADNNNNNSSZZZZEEEEEEEEEEEXXXJJJJJJJJJJJJJQIIIMEEEEEEEAAAAAEESSSYVVVVVVVVVVWVHHHHH
WWWWWNNVVVVVVJJJJJJJJIIIIIIDDDRRRRRRNNNNNNNNNNNAAAAAAAAAAAAAADNNNNNSSSZZZEEEEEEEEEEFXSSJJJJJJJJJJJJJQQDSMMMEEEEEAAAAAESSSYYYVVVVVVVVVVVHHHHH
WBWWWNNNVVVVJJJJJJJJJIIIIDDDDRRRRRRRNNNNNNNNNNEAAAAAAAAAAAAAANNNNNNZZZZZEEEEEEEEEEEEXSSJJJJJJJJJJJJJQQSSSSSSEEEEAAAAAEESSVVVVVVVVVVVVVVHHHHA
BBWWWNNNVVJJJJJJJJJJJIIDDDDDRRRRRRRNNNNNNNNNNNEEEAAAAAAAAAAAANNNNNNSSSSEEEEEEEQEEENNNSSSJJJJJJJJJJJJQQSSSSSEEEEEAAAAEEEEVVVVVVVVVVVVVVHHHHHA
BBWWWWNNNNNJJJJJJJJJIIIDDLLORRRRRRRRNNNNNNNNNNEEEAAAAAAAAAAAANNNNNNNNNEEEHHHEEEEEEEEESSSJJJJJJJJJJJJQSSSSPPPEPEEAAAAEEEEVVVVVVVVVVVVVVAAAAHA
CBBBGGNGGNNNJJJJJJJJJILLLLLLQLRRRRROOOONNYNEEEEEAAAEEAAAAAAEENNNVVNNNNHHHHHEEEEEEEEESSSJJJJJJJJJJJJJSSSSSPPPPPPPAAAAEEEEEVVVVVVVVVSSVVVAAAAA
CBBBGGGGGNNNNJJXJJJJJXBBBBLLLLRRRRRROOOONNNEOEEEEAAEEAAAAAAEEENNNVNNNNNNNHHEEEEESSSSSSSJJJJJJJJJSSSSSSSSSPPPPPPPPPEEEEEOOVVVVVVVSSSAAAAAAAAA
CCBBGGGGGNNNNJXXJXXXXXBBBKLLLFRURRUUOOOOONOOOOOEEEEEEAEAAAEEENNNNNNNNNNNNEHEEEHEESSSSSSJJJJJSSSSSSSSSSSSPPPPPPPPPEEEEEEEOAAVVVVVVVAAAAAAAAAA
CCBGGGGGGGNNXXXXXXXXXBBKBKKLLKUUUUOOOOOOOOOOOOOEEEEEEAEAEEEENNNNNNNNNNNNREEEEHHEESSSSSSJJJJJSSSSSSSSSSSSPPPPPPPPPEEEEEEEERAAAAAVAAAAAAAAAAAA
CCCCGGGGGGNNXXXXXXXXXKKKKKKKLKKUUUUOOOOOOOOOOEEEEEEEEEEAEEEEEENNNNNNNNNNNNNJJIHHEHSWSSSJJJJJSSSSSSSSSPPMPPPPPPPPPEEEEEEEERAAAAAAAAAAAAAAAAAA
CCCCGGGGGGGGXXXXXXXXXKKKKKKKKKKUUUUUDDOOOOOOOEEEEEEEEEEEEEEENNNNNNNNNNNNNJJJJIHHHHSWWSSJJJJJSKKKKSSSSSPPPPPPPPPPPVVEEEEEEEAAADAAAAAAAAAAAAAA
CCCCGGGGGGGGXXXXXXXXXKKKKKKKKKKKKUUUDDOOOOOOOOEEEEEEEEEEEREEENNNNNNNNNNNNJJJIIIIISSSSVSSSRRSSKKKKSKSSPPZPPPPPPPPPPVEEEEEFFFADDADAAAAAAAAAAAA
CCCGGGGGGGGGXXXXXXXXXXXKKKKKKKKKKKDDDNNOOOOOOEEEEEEEEEEEEREEENNNNNNNNNNXWJJJIIIIVVVVVVVVSKKKKKKKKSKKKKKZZPPPPPPPPPEEOEEEEFFDDDDDDDAAAAAAAAAA
CCCCGGGGGGGGFXXXXXXXXKKKKKKKKKKKDDDDDNNNOOOOEEEEEELEEEEEERRRRRNNNNNNNNNXWJJJIIIIIIVVVVVIIKKKKKKKKKKKKKKKPPPPEEEPPPEEELEEEEDDDDDDDDAAAAAAAJAA
CCCGGGGGGGGGFFXXLLXXKKKKKKKKKKKDDDDDDNNOOOOOEEEELLLLLLEEEERERRRNNNYNNNNWWWWIIIIIIIVIIIVIIYKKKKKKKKKKLLLKKPPPPEEEEPEEZEEEECDDDDDDDDAAAAAAXAAA
CCCCGGGGGGGLLFFLLLLXXKKKKKKKKKKDDDDDNNOOOOOEELLLLLLLLLEEEEEEENNNNNMMMNNWWWIIIIIIIIIIIIIIBKKKKKKKKKKLLLKKEPEEEEEEEEEEEEEAEDDDDDDDDDDAXAXXXAAA
CCCCGGGGGGLLLLLLLLXXDDKKKKKDKDDDDDDDDNNNNNNNNLLLLLLLLLEEEEEZENNRRRMLLLWWWWWWWIIIIIIIIIIIBKKKKKKKKKKKLLLLEEEEEEEEEEEEEEEAEADDDDDDDDDXXXXXXXXC
CCCCGGGGGGWLLLLLLLXDDKKKKKKDKDDDDDDIIINNNNNNLLLLLLLLLLEEEEZZNNNMMMMLMMMWWWWWWIIIIIIIIQIBBBKKKKKKKKKKKKLLEEEEEEEEEEEEEPPAAADDDDDDDXXXXXXXXXXC
CCCCGFGGGGWLLLLLLLLDDKKKDDDDDDDDDIIIIINNNNNNNLLLLLLLLLLEZZZMMMMMMMMMMMMGWWWWIIIIIIIIIQQQBBKKKKKKKKKKKKKLEEEEEEEEEEEEEEPAAADDDDDDDXXXXXXCCCCC
CCCCCLLMGLLLLLLLLLLDDDKDDWDDDDDNNNNIIIIIIINNNNNLLLSSLSLZZZZZMMMMMMMMMMMMMWWWIIIIIIIIIIQQBBBKKKKKKKKKKKKKEEEEEEEEEEEEEPPPPADDDDDHDXXXXXMMMCCC
CCLLLLLLLLLLLLLLLLLDDDKDDWWDWWWWNNNIIIIINNNNNNLLNLSSSSLLZZZMMMMMMMMMMMMMMWWWWIIIIIIIIKQQBBQKKKKKKKKKKKKKEEEEEEEEEEPEEEPPPDDDDDDDDXXXXXXMMMMM
CCCCLLLLLLLLLLLLLLLDDDDDWWWWWWPPNNNIIIIJNNNNNNNNNLSSSULLZZZZMMMMMMMMMMMMMMWWIIIQIQIQQQQQBBQMKKKKKKKKKKKKEEEEEEEEEEPEEPPPDDDDDTDDDXXXXXXMMMMM
CCCCLLLLLLLLLLLLLLLDDDDDDWWWWWWITIIIIIIINNNNNNNNNNSNSUZZZZZMMMMMMMMMMMMMMMWWIIQQQQQQQQQQQBQQXKKKKVVHHKKKKEEEEZEEEEPPPPPPPDDDDDDDXXXXXXXMMMMM
CCCCCLLLLLLLLLLLLLLLLLDDDWWWWWWIIIIIIIIINNNNNNNNNNNNNQQZZZZZMMMMMMMMMMMMMMWWIIZZQQQQQQQQKQQQXXKKVVHHHHHHEEEEEZSEEEPPPPPVPPDVXXXXXXXMXXXMMMMM
CCCCCLTLLLLLLLLLLLPLDDDDDWWWWWWIIIIIIIIINNNNNNNNNNNNQQZZZZZZMMMMMMMMMMMMMMMMZZZQQQQQQQQQQQQXXXXXHHHHHHHHHHZZZZSEPPPPPPPVVVVVVVXXXXXMMMMMMMMM
CCCCCCTTLLLLLLLLTLLDDDDDDDWWWWWWWIIIIIINNNNNNNNNNNNNQQQQQQQQQMMMMMMMOOOMMMMZZZQQQQQQQQQBBQQXXHHHHHHHHHHHHHZZZZZZPPPPPPPVVVVVVVVXVVXMMMMMMMMM
CCCCCCCLLLLLLLLLTLLDDDWWWDWWWWWWWIWTIINNNNNNNNNNNNNNQQQQHQQQKKKKKOMOOXOMMMMZZZZQQQQQQQQQQQQQXHHHHHHHHHHHGZZZZZLZPPPPPPPXNVVVVVVVVVMMMMMMMMMM
RRCCCCRRLYLLLLTTTIDDDDWWWWWOWWWWWWWWIIWNNNNNNNNNNNNNQQQQQQQQQQKKKOOOOOOMMMMZZZZZQQQQQQQQQQQQHHHHHHHHHHHHGZZZZZZZPPPPXXPXVVVVVVVVVVMMMMMMMMMM
RCCCRRRLLYRAALLTRIIIIIBWWWWWWWWWWWWWWWWNNNNNNNXNNNNQQQQQQQQQQKKKKKOOOMMMMMMMZZZZQQQQQQQQQQQQWHHHHHHHHHHHHZZZZZZZYPPPXXXXDVVVVVVVVVVMMMMMMMMM
RRRCRRRRRRRRRZRRRIIIIIBBWWZWWWWWWWWWWWNNNNNNNXXXNNNQQQQQQQQQKKKKKKOOOOMMMMMMZKKKKKQQQQQQQQQQWWHHHHHHHHHHSZZZZZZZMPPPXXXXXVVXMMVVVVMMMMMMMMMM
RRRRRRRRRRRRRRRRIIIIIIBWWWZZWWWWWWWWWNNNNNNTTXXNNNQQQQQQQQQQQQNNNNNOOOMMMMMMZZZZZZQQQQQQQQQWWWHHHHHHHHHSSZZZZZZMMMMMXXXXXXXXMMVVVVTMMMMMMMMM
RRRRRRRRRRRRRRFRIIIIIIBBBWWZZWWWWWWWWNNNNNTTTXNNQQQQQQQQQQQQQQZNNNNNNNMMMMMMMZZZZZQWWQQQQQQWWWWHHHHHHHHHSZZZMZMMMXXXXXXXXXXXXXXXVCMMMMMMMMMM
RRRRRRRRRRRRRRRIIIIIIIIBBWWZZZWWWWWWWWWNCTTTTTQQQQQQQQQQQQQQQSNNNNNNNNNNMMMMMMGGGGQWWWWQQQQWWWWHLHHHHHHSSSZMMMMMMXXXXXXXXXXXXXXCVCMMMMMMMMMM
RRRRRRRRRRRRRRRIIIIIIIISBBBIZZZWWWWWWWTTTTTTTTQQQQQQQBBQQMQPQNNNNNNNNNNNMMMMMMGIGGGGWWWQQVQLLLWLLHHHHHHHSMMMMMMMMMXXXXXXXXXXXXCCCCMMMMMMMMMM
RRRRRRRRRRRRRRRIIIIIIGSSBBIIIIZZWWWWWTTTTTTTTTTQQQGQQBBQQQQQHNNNNNNNNNNNMMMGGGGGGGGGWWWWQQTTLLLLLHUHHHHHSMMMMMMMMMJJTXTTXXXXXXCCLLKKMMMMMMMM
RRRRRRRRRRRRRRCIIIIISSSSBBSIIIIIWWWWWWITTTTTTTTTQQGQQBBBQQQNHNNNNNNNNNNNNMMMMGGGGGGGGGWTTTTTTTLLLLUHHHHSSMMMMMMMMMJJTTTTXXXXXLLLLLKLLMMMMMTM
RZRRRRRRRRRRRRIIIIIIIISSSSSIIIIIWWWIIIITTTTTTTTTTTGQAGBBQBQNNNNNNNNNNNNNNNMMMGGGGGGGGTTTTTTTTTLLLTTHHHHSMMMIMMMJMJJJJTTTXXXXXZZLLLLLLWMWMMMZ
ZZRRRRJRRRRRRRIIIIIIIISSSSSIIIIIWIIIIIIIIITTTTGGGGGGGGBBBBBNNNNNNNNNNNNNNNMMMMMGGGGGGTTTTTTTTTLLTTTHLAAAAMMAJJJJJJJJTTTTXXXXXLLLLLLLLWWWMMMM
ZZZRRRJJRRRRRIIIIIIISSSSSSIIIIIIIIIIIGGIIIIITTGGGGGGGGGGGBBBNNNNNNNNNNNNNMMMMMMMMGGGTTTTTTTTTTTTTTAAAAAAAMAAJJJJJJJJTTTTXXXXXXLLLLLLLLWWMMWW
ZZZRZZJJJJRJIIIIIIIIISPSSSFPIIIIIIIIIGGIIIIGGGGGGGGGGGGGGBNNNNNNNNNNNNWNMMMMMMMMMMMTTTTTTTTTTTTTTTTAAAAAAQAAAAAJJJJJJJTXXXXXXXLLLLLLLLLWWWWW
ZZZZZJJJJJJJJJJIIIIIIIIJSFFFIIIIIIIIIGIIIIIGGGGGGGGGGGGGGGQYNNNNNNNYNNYNMMMMMMMMMMMTDTTTTTTTTTTTTTAAAAAAAAAAAAAJJJJXXXXXXXXXXXLLLLLLLFLWWWWW
CZZZZJJJJJJJJJIIIIIIJIJJFFFFIIIIIIIIIIIIIIGGGGGGGGGGGGGGGYYYYYYNNNNYYYYYYYDMMMMMMMMMDDTTTTTTTTTTTTAAAAAAAAAAAAJJJJJXXXXXXXXXAAAALLLLLLLLWWWW
CZZZZJJZZJJJJJJJJIIIJIJFFFFFIIIIIIIIIIIIIIIGGGGGGGGGGGGGGYYYYYYYYYYYYYYYYYDMMMMMMMMDDDDTTTTTTTTTTTADAAAAAAAAYJJJJJJJJXXXXXXXXXXALLLLLLXBBWWW
ZZZZZZZZAZJJJRJRRRIIJJJOWWYYIIIIIIIIOOIIIIGGGGGGGGGGGGAAAYYYYYYYYYYYYYYYYYYMMXMMMMDDDDDDDDTTDDTTTTDAAAAAAAAAYJJJJJJJWWWXWWWXXAAAAALLYLXBBWBB
ZZZZZZZZAZJRRRRRRJJIJJOOWWYYIIYIOOOOOOOIIGGGGGGGGGGGAGAAYYYYYYYYYYYYYYYYYYYYMMMMEDDDDDDDDDDDDDDDTDDDAAAAAAAAADJJJJJJWWWWWWWWAAAAALLLLLLBBBBB
ZZZZZZZZZZJJRRRJJJJJJOOOWYYYYYYIOOOOOOOOGGGGGGGGGGGGAGAAAYYYYYYYYYYSYYYYYYYEEEMEEEEDDDDDDDDDDDDDDDDDDAAAAAADDDDJDJKWWWWWWWAAAAAALLLSBBBBBBBB
ZZZZZZZZZJJWWWWJJJJOJOOOOOOCYYBOOOOOOOOOGGSGGGGGGGGGAAAAYYYYYYYYYYSSSSYYEEEEEEEEEEDDDDDDDDDDDDDDDDDDDAADDDDDDDDDDKKKWKKWWWWWAAAAALLSBBBBBBBB
ZZZZZZZZZZZWWWWJJJJOOOOOOOOOOFOOOOOOOOOOOGGGGGGDDDQQQQQAAYYYYYYYYSSSSSSYEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDKKKKKKKKKWWWXXAAAAASSSSBBBBBBB
ZZZZZZZZZWWWWWWWWJOOOOOOOOOOIOOOOOOOOOOOGBBBGGGDDQQQQQQQYYYYYYYYYYGSSSSSSSEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDKKKKKKKKKKWWXXXAAAAAASSSBBBBBBB
ZZZZZZWWWWWWWWWWJJOOOOOOOOOOOOAOOOOOOOOBBBBBGTSSDQQQQQQQYYYYYYYYOOCCSSSSSEEEEEEEEEDDDDDDDDDDDDDDEDDDDDDDSDDDDKEKKKKKKKKXXXXXWWWAAABBBBBBBBBB
ZZZZZZWWWWWWWWWWJJOOOOOOOOOOOOOOOOOOOBBBBBBBBSSSSQQQQQQQYVYYYYYYYOOCCCSSCEEEEEEEEEEDDDDDDDDDDDDDEEEDSSDDSDDDKKKKKKKKKKKXXXXXWWWWBUBBBBBBBBBB
SZZZZZZWWWWWWWWSOOOOOOOOOOOOOOOOOOOOBBBBBBBBBSSSQQQQQQQQYYYYYYYMYOOCCCSSCCCCCCCEEEEDDDDDDDDDDDDEEEEEPSSSSDKKKKIKKKKKKKKBXXXXXWWWBBBBBBBBBBBB
ZZWWWWZWWWWWWWWWOOOOOOOOOOOOOOOOOOOOOOOBBBBBBBBBQQQQQQQQQYYYYOOYYOKKCCCCCCCCCCCCEEEDDDDDDDDZEEEEEEESSSSSSSSSDKKKKKKKKKKXXXXXXWWWWWWBBBBBBBBB
ZWWWWWWWWWWWWWWWWNNNOOOOOOOOOOOOOOOOOOBBBBBBBBBBQQQQQQQQQQQQYOOOOOKKKCCCCCCCCCCEEEEDDDEDDDDDEEEEEEFSSSSSSSSSSKKKKKKKKKXXXXXXWWWWWWWBBBBBBBBB
MWWWWWWWWWWWWWWNNNNNOOOOOOOOOOOOOOOOOOBOBBBBBBBBBSQQQQQQQQQQQOOOOOCCKKCCCCCCCCCEEEEEEEEEEDDEEEEEEEEESSSSSSSSKKKKKKKKKKXXXXXWWWWWWBBBBBBBBBBB
MMWWWWWWWWWWWWWWWNNNOOOOOOOOOOOOOOOOOOOOBBBBBBBBBBQQQQQQQQQQQOOOOOCCCCCCCCCCLLCEEEEEEEEEEEEEEEEEEEEEMSSSSSISRKIIKKKKGKXXXXXXXWWWWBBBBBBBBBBB""";
}
