package nl.jiankai.year2022;

import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;

public class Day2 {
    public static void main(String args[]) {
        part1();
        part2();
    }

    private static void part1() {
        System.out.println(
                input
                        .stream()
                        .mapToInt(line -> {
                            String[] opponentAndMyMove = line.split(" ");
                            Move opponentsMove = Move.getMove(Move.toMoveType(opponentAndMyMove[0].charAt(0)));
                            Move myMove = Move.getMove(Move.toMoveType(opponentAndMyMove[1].charAt(0)));
                            return myMove.computeScore(opponentsMove);
                        })
                        .sum());
    }

    private static void part2() {
        System.out.println(
                input
                        .stream()
                        .mapToInt((line) -> {
                            String[] opponentMoveAndStrategicMove = line.split(" ");
                            Move opponentsMove = Move.getMove(Move.toMoveType(opponentMoveAndStrategicMove[0].charAt(0)));
                            Move myMove = Move.getStrategicMove(opponentsMove, opponentMoveAndStrategicMove[1].charAt(0));
                            return myMove.computeScore(opponentsMove);
                        })
                        .sum());
    }

    private interface Move {
        enum MoveType {
            ROCK, PAPER, SCISSOR
        }

        MoveType move();

        MoveType losesAgainst();

        MoveType winsAgainst();

        default boolean wins(Move move) {
            return winsAgainst() == move.move();
        }

        default boolean draws(Move move) {
            return move() == move.move();
        }

        int score();

        static MoveType toMoveType(char move) {
            return switch (move) {
                case 'A', 'X' -> MoveType.ROCK;
                case 'B', 'Y' -> MoveType.PAPER;
                case 'C', 'Z' -> MoveType.SCISSOR;
                default -> throw new IllegalArgumentException("Unexpected value: " + move);
            };
        }

        static Move getStrategicMove(Move opponentsMove, char strategicMove) {
            return switch (strategicMove) {
                case 'X' -> getMove(opponentsMove.winsAgainst());
                case 'Y' -> getMove(opponentsMove.move());
                case 'Z' -> getMove(opponentsMove.losesAgainst());
                default -> throw new IllegalArgumentException("Unexpected value: " + strategicMove);
            };
        }

        default int computeScore(Move opponentsMove) {
            if (wins(opponentsMove)) {
                return 6 + score();
            } else if (draws(opponentsMove)) {
                return 3 + score();
            } else {
                return score();
            }
        }

        static Move getMove(MoveType move) {
            return switch (move) {
                case ROCK -> new Move() {
                    @Override
                    public MoveType move() {
                        return move;
                    }

                    @Override
                    public MoveType losesAgainst() {
                        return MoveType.PAPER;
                    }

                    @Override
                    public MoveType winsAgainst() {
                        return MoveType.SCISSOR;
                    }

                    @Override
                    public int score() {
                        return 1;
                    }
                };
                case PAPER -> new Move() {
                    @Override
                    public MoveType move() {
                        return move;
                    }

                    @Override
                    public MoveType losesAgainst() {
                        return MoveType.SCISSOR;
                    }

                    @Override
                    public MoveType winsAgainst() {
                        return MoveType.ROCK;
                    }

                    @Override
                    public int score() {
                        return 2;
                    }
                };
                case SCISSOR -> new Move() {
                    @Override
                    public MoveType move() {
                        return move;
                    }

                    @Override
                    public MoveType losesAgainst() {
                        return MoveType.ROCK;
                    }

                    @Override
                    public MoveType winsAgainst() {
                        return MoveType.PAPER;
                    }

                    @Override
                    public int score() {
                        return 3;
                    }
                };
            };
        }
    }

    private static final List<String> input =
            Arrays.asList(("C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "C X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Z\n").split("\n"));
}
