package nl.jiankai.year2022;

import java.util.Arrays;
import java.util.List;

public class Day2 {
    public static void main(String args[]) {
        part1();
        part2();
    }

    private static void part1() {
        int total = 0;

        for (String line : input) {
            total += determineScore(line);
        }

        System.out.println(total);
    }

    private static void part2() {
        int total = 0;

        for (String line : input) {
            total += determineScore2(line);
        }

        System.out.println(total);
    }

    private static int determineScore(String line) {
        String[] rps = line.split(" ");
        char opp = rps[0].charAt(0);
        char me = toOpp(rps[1].charAt(0));

        return computeScore(opp, me);
    }

    private static int determineScore2(String line) {
        String[] rps = line.split(" ");
        char opp = rps[0].charAt(0);
        char scenario = rps[1].charAt(0);
        char me = computeResponse(opp, scenario);

        return computeScore(opp, me);
    }

    private static int computeScore(char opp, char me) {
        if (opp == me) {
            return 3 + rpsScore(me);
        } else if ((opp == 'A' && me == 'C')
                || (opp == 'B' && me == 'A')
                || (opp == 'C' && me == 'B')) {
            return rpsScore(me);
        } else {
            return 6 + rpsScore(me);
        }
    }

    private static char toOpp(char me) {
        return switch (me) {
            case 'X' -> 'A';
            case 'Y' -> 'B';
            case 'Z' -> 'C';
            default -> throw new IllegalStateException("Unexpected value: " + me);
        };
    }

    private static char computeResponse(char opp, char scenario) {
        return switch (scenario) {
            case 'X' -> getLosingMove(opp);
            case 'Y' -> opp;
            case 'Z' -> getWinningMove(opp);
            default -> throw new IllegalStateException("Unexpected value: " + scenario);
        };
    }

    private static char getWinningMove(char opp) {
        return switch (opp) {
            case 'A' -> 'B';
            case 'B' -> 'C';
            case 'C' -> 'A';

            default -> throw new IllegalStateException("Unexpected value: " + opp);
        };
    }

    private static char getLosingMove(char opp) {
        return switch (opp) {
            case 'A' -> 'C';
            case 'B' -> 'A';
            case 'C' -> 'B';
            default -> throw new IllegalStateException("Unexpected value: " + opp);
        };
    }

    private static int rpsScore(char rps) {
        return switch (rps) {
            case 'A' -> 1;
            case 'B' -> 2;
            case 'C' -> 3;
            default -> 0;
        };
    }

    private static final List<String> input =
            Arrays.asList(("C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "C X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Z\n").split("\n"));
}
