package nl.jiankai.year2022;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public class Day9 {
    public static void main(String[] args) {
        part2();
    }

    private static void part2() {
        Set<String> visited = new HashSet<>();
        int[][] positions = new int[10][2];


        for (String move : input) {
            String[] split = move.split(" ");
            int n = Integer.parseInt(split[1]);
            for (int i = 0; i < n; i++) {
                if (split[0].equals("R")) {
                    positions[9][0]++;
                } else if (split[0].equals("L")) {
                    positions[9][0]--;
                } else if (split[0].equals("U")) {
                    positions[9][1]--;
                } else if (split[0].equals("D")) {
                    positions[9][1]++;
                }

                for (int j = 8; j >= 0; j--) {
                    int tX = positions[j][0], tY = positions[j][1];
                    int hX = positions[j + 1][0], hY = positions[j + 1][1];
                    int dx = Math.abs(tX - hX);
                    int dy = Math.abs(tY - hY);
                    if (dx > 1 && dy == 0) {
                        if (tX > hX) {
                            tX--;
                        } else {
                            tX++;
                        }
                    } else if (dy > 1 && dx == 0) {
                        if (tY > hY) {
                            tY--;
                        } else {
                            tY++;
                        }
                    } else if (((dx > 1 || dy > 1) && Math.abs(dx - dy) >= 1) || (dx > 1 && dy > 1)) {
                        if (tX < hX) {
                            tX++;
                            tY = tY < hY ? tY + 1 : tY - 1;
                        } else if (tX > hX) {
                            tX--;
                            tY = tY < hY ? tY + 1 : tY - 1;
                        } else if (tY > hY) {
                            tX = tX - 1;
                            tY--;
                        } else if (tY < hY) {
                            tX = tX - 1;
                            tY++;
                        }
                    }

                    positions[j][0] = tX;
                    positions[j][1] = tY;
                    if (j == 0) {
//                        boolean newPosition = !visited.contains("(%s, %s)".formatted(tX, tY));
                        visited.add("(%s, %s)".formatted(tX, tY));
//                        System.out.println(Arrays.stream(positions).map(arr -> "(%s, %s)".formatted(arr[0], arr[1])).collect(Collectors.joining(", ")));
//                        System.out.println("Direction: %s - %s ".formatted(split[0], n - i));
                    }
                }
//                drawState(positions);
            }
        }

        System.out.println(visited.size());
    }

    private static void drawState(int[][] p) {
        int[][] m = new int[35][50];
        for (int i = 0; i < p.length - 1; i++) {
            m[p[i][1] + 20][p[i][0] + 20] = 9 - i;
        }
        m[p[9][1] + 20][p[9][0] + 20] = 10;

        for (int i = 0; i < m.length; i++) {
            System.out.print(i+1);
            for (int j = 0; j < m[i].length; j++) {
                int z = m[i][j];
                if (z > 0 && z <= 9) {
                    System.out.print(z);
                } else if (z == 10) {
                    System.out.print("H");
                } else {
                    System.out.print(".");
                }
            }
            System.out.println();
        }
    }

    private static List<String> input = Arrays.asList(("L 1\n" +
            "D 2\n" +
            "R 2\n" +
            "L 1\n" +
            "D 1\n" +
            "L 1\n" +
            "U 1\n" +
            "R 1\n" +
            "L 2\n" +
            "R 2\n" +
            "L 2\n" +
            "D 1\n" +
            "R 2\n" +
            "D 1\n" +
            "U 2\n" +
            "R 2\n" +
            "D 1\n" +
            "R 1\n" +
            "L 2\n" +
            "R 1\n" +
            "D 1\n" +
            "U 2\n" +
            "R 2\n" +
            "D 1\n" +
            "R 2\n" +
            "L 1\n" +
            "D 1\n" +
            "U 1\n" +
            "R 1\n" +
            "D 2\n" +
            "L 1\n" +
            "D 1\n" +
            "L 1\n" +
            "U 1\n" +
            "L 2\n" +
            "U 1\n" +
            "L 1\n" +
            "U 1\n" +
            "L 1\n" +
            "D 2\n" +
            "R 2\n" +
            "U 1\n" +
            "D 2\n" +
            "R 1\n" +
            "U 1\n" +
            "D 1\n" +
            "R 1\n" +
            "U 2\n" +
            "L 2\n" +
            "D 2\n" +
            "R 1\n" +
            "U 2\n" +
            "L 2\n" +
            "U 1\n" +
            "D 1\n" +
            "L 1\n" +
            "R 2\n" +
            "L 2\n" +
            "R 1\n" +
            "D 2\n" +
            "L 1\n" +
            "D 2\n" +
            "L 1\n" +
            "R 2\n" +
            "U 2\n" +
            "D 2\n" +
            "U 1\n" +
            "R 2\n" +
            "D 2\n" +
            "L 2\n" +
            "U 1\n" +
            "D 2\n" +
            "R 1\n" +
            "L 2\n" +
            "R 1\n" +
            "L 2\n" +
            "U 2\n" +
            "D 2\n" +
            "U 2\n" +
            "D 2\n" +
            "R 1\n" +
            "U 2\n" +
            "L 2\n" +
            "D 1\n" +
            "U 2\n" +
            "L 1\n" +
            "D 1\n" +
            "R 2\n" +
            "U 1\n" +
            "L 1\n" +
            "D 1\n" +
            "U 2\n" +
            "D 2\n" +
            "R 2\n" +
            "U 1\n" +
            "L 2\n" +
            "D 2\n" +
            "L 1\n" +
            "D 2\n" +
            "L 1\n" +
            "U 1\n" +
            "R 2\n" +
            "L 2\n" +
            "D 1\n" +
            "R 2\n" +
            "U 2\n" +
            "R 2\n" +
            "L 2\n" +
            "D 1\n" +
            "R 1\n" +
            "L 1\n" +
            "D 2\n" +
            "U 2\n" +
            "L 1\n" +
            "D 1\n" +
            "R 1\n" +
            "L 3\n" +
            "U 2\n" +
            "R 2\n" +
            "D 3\n" +
            "L 1\n" +
            "R 3\n" +
            "L 1\n" +
            "R 2\n" +
            "D 1\n" +
            "U 3\n" +
            "L 1\n" +
            "U 2\n" +
            "L 1\n" +
            "D 3\n" +
            "R 3\n" +
            "D 1\n" +
            "U 3\n" +
            "R 2\n" +
            "D 2\n" +
            "R 2\n" +
            "L 1\n" +
            "U 1\n" +
            "R 1\n" +
            "U 2\n" +
            "R 3\n" +
            "U 1\n" +
            "D 1\n" +
            "U 1\n" +
            "R 3\n" +
            "D 2\n" +
            "R 2\n" +
            "U 3\n" +
            "D 1\n" +
            "R 3\n" +
            "L 3\n" +
            "U 3\n" +
            "D 3\n" +
            "R 1\n" +
            "D 3\n" +
            "L 1\n" +
            "D 3\n" +
            "L 1\n" +
            "R 1\n" +
            "U 1\n" +
            "L 2\n" +
            "D 3\n" +
            "U 3\n" +
            "D 2\n" +
            "U 3\n" +
            "D 2\n" +
            "U 2\n" +
            "D 1\n" +
            "R 2\n" +
            "U 3\n" +
            "L 1\n" +
            "R 2\n" +
            "L 3\n" +
            "U 3\n" +
            "D 3\n" +
            "L 2\n" +
            "R 2\n" +
            "U 3\n" +
            "R 1\n" +
            "L 1\n" +
            "U 1\n" +
            "D 1\n" +
            "R 2\n" +
            "L 3\n" +
            "U 3\n" +
            "D 1\n" +
            "L 1\n" +
            "U 1\n" +
            "R 1\n" +
            "D 2\n" +
            "L 2\n" +
            "D 2\n" +
            "R 3\n" +
            "D 2\n" +
            "R 3\n" +
            "D 2\n" +
            "R 1\n" +
            "D 1\n" +
            "R 3\n" +
            "D 1\n" +
            "U 1\n" +
            "L 1\n" +
            "R 2\n" +
            "D 3\n" +
            "L 3\n" +
            "R 1\n" +
            "L 2\n" +
            "R 1\n" +
            "U 3\n" +
            "D 2\n" +
            "R 1\n" +
            "U 1\n" +
            "L 2\n" +
            "R 2\n" +
            "L 2\n" +
            "D 1\n" +
            "U 3\n" +
            "R 3\n" +
            "D 2\n" +
            "R 1\n" +
            "U 2\n" +
            "L 3\n" +
            "R 1\n" +
            "D 1\n" +
            "U 2\n" +
            "L 4\n" +
            "D 2\n" +
            "R 1\n" +
            "U 4\n" +
            "R 4\n" +
            "D 3\n" +
            "R 3\n" +
            "U 2\n" +
            "L 2\n" +
            "U 1\n" +
            "D 3\n" +
            "U 2\n" +
            "D 2\n" +
            "R 4\n" +
            "D 3\n" +
            "R 3\n" +
            "D 4\n" +
            "R 2\n" +
            "U 2\n" +
            "L 1\n" +
            "D 1\n" +
            "L 2\n" +
            "U 4\n" +
            "D 4\n" +
            "R 3\n" +
            "U 2\n" +
            "R 3\n" +
            "U 4\n" +
            "D 2\n" +
            "R 3\n" +
            "D 4\n" +
            "L 3\n" +
            "D 1\n" +
            "R 4\n" +
            "D 4\n" +
            "R 4\n" +
            "L 3\n" +
            "U 1\n" +
            "L 1\n" +
            "D 4\n" +
            "L 3\n" +
            "D 1\n" +
            "U 2\n" +
            "R 4\n" +
            "U 1\n" +
            "L 4\n" +
            "D 3\n" +
            "U 2\n" +
            "R 4\n" +
            "D 3\n" +
            "U 3\n" +
            "L 4\n" +
            "U 2\n" +
            "R 1\n" +
            "U 1\n" +
            "D 3\n" +
            "R 3\n" +
            "D 1\n" +
            "U 1\n" +
            "L 3\n" +
            "R 1\n" +
            "D 2\n" +
            "R 4\n" +
            "U 2\n" +
            "D 4\n" +
            "U 4\n" +
            "L 4\n" +
            "R 4\n" +
            "D 2\n" +
            "R 3\n" +
            "D 3\n" +
            "R 4\n" +
            "U 1\n" +
            "D 3\n" +
            "R 4\n" +
            "L 1\n" +
            "U 1\n" +
            "L 1\n" +
            "D 4\n" +
            "R 1\n" +
            "U 4\n" +
            "L 3\n" +
            "R 2\n" +
            "U 4\n" +
            "R 3\n" +
            "U 1\n" +
            "L 3\n" +
            "D 2\n" +
            "L 2\n" +
            "R 3\n" +
            "D 1\n" +
            "L 4\n" +
            "D 2\n" +
            "R 3\n" +
            "L 4\n" +
            "R 4\n" +
            "L 2\n" +
            "U 1\n" +
            "D 1\n" +
            "R 3\n" +
            "U 4\n" +
            "D 4\n" +
            "U 4\n" +
            "D 4\n" +
            "R 4\n" +
            "U 4\n" +
            "D 1\n" +
            "U 1\n" +
            "D 4\n" +
            "U 1\n" +
            "D 4\n" +
            "U 4\n" +
            "R 4\n" +
            "D 4\n" +
            "L 4\n" +
            "D 1\n" +
            "U 5\n" +
            "R 5\n" +
            "U 5\n" +
            "L 1\n" +
            "R 4\n" +
            "U 5\n" +
            "L 2\n" +
            "U 4\n" +
            "D 1\n" +
            "R 1\n" +
            "L 4\n" +
            "D 2\n" +
            "L 5\n" +
            "D 5\n" +
            "R 3\n" +
            "L 2\n" +
            "R 1\n" +
            "U 1\n" +
            "R 5\n" +
            "D 2\n" +
            "U 1\n" +
            "L 1\n" +
            "D 4\n" +
            "U 4\n" +
            "L 2\n" +
            "U 4\n" +
            "L 1\n" +
            "D 4\n" +
            "L 1\n" +
            "U 4\n" +
            "L 3\n" +
            "U 3\n" +
            "D 2\n" +
            "L 3\n" +
            "D 2\n" +
            "L 3\n" +
            "R 1\n" +
            "L 2\n" +
            "U 1\n" +
            "L 2\n" +
            "R 2\n" +
            "D 5\n" +
            "U 4\n" +
            "R 1\n" +
            "D 5\n" +
            "U 2\n" +
            "R 3\n" +
            "U 4\n" +
            "L 4\n" +
            "R 5\n" +
            "L 2\n" +
            "R 5\n" +
            "U 5\n" +
            "D 3\n" +
            "R 2\n" +
            "D 1\n" +
            "R 2\n" +
            "U 4\n" +
            "D 1\n" +
            "R 4\n" +
            "D 5\n" +
            "R 4\n" +
            "L 4\n" +
            "U 5\n" +
            "D 1\n" +
            "L 2\n" +
            "R 1\n" +
            "U 3\n" +
            "L 5\n" +
            "R 5\n" +
            "L 2\n" +
            "D 3\n" +
            "L 2\n" +
            "R 3\n" +
            "U 2\n" +
            "D 2\n" +
            "U 3\n" +
            "L 5\n" +
            "U 3\n" +
            "D 1\n" +
            "R 1\n" +
            "D 3\n" +
            "L 2\n" +
            "U 1\n" +
            "D 2\n" +
            "U 4\n" +
            "L 4\n" +
            "U 5\n" +
            "R 5\n" +
            "U 5\n" +
            "L 5\n" +
            "R 3\n" +
            "L 1\n" +
            "D 1\n" +
            "L 3\n" +
            "D 4\n" +
            "R 1\n" +
            "D 1\n" +
            "R 3\n" +
            "L 4\n" +
            "U 4\n" +
            "L 1\n" +
            "R 5\n" +
            "D 4\n" +
            "U 2\n" +
            "D 6\n" +
            "U 6\n" +
            "L 6\n" +
            "U 2\n" +
            "L 2\n" +
            "D 6\n" +
            "U 2\n" +
            "R 2\n" +
            "U 1\n" +
            "R 6\n" +
            "D 6\n" +
            "R 5\n" +
            "L 4\n" +
            "R 3\n" +
            "D 4\n" +
            "L 6\n" +
            "U 1\n" +
            "D 2\n" +
            "L 5\n" +
            "U 2\n" +
            "D 1\n" +
            "U 6\n" +
            "R 4\n" +
            "L 4\n" +
            "U 3\n" +
            "L 3\n" +
            "U 6\n" +
            "L 4\n" +
            "R 4\n" +
            "L 5\n" +
            "U 2\n" +
            "L 1\n" +
            "U 1\n" +
            "D 5\n" +
            "U 4\n" +
            "D 5\n" +
            "L 5\n" +
            "U 3\n" +
            "R 6\n" +
            "U 5\n" +
            "D 6\n" +
            "R 3\n" +
            "D 1\n" +
            "L 3\n" +
            "R 5\n" +
            "U 5\n" +
            "R 4\n" +
            "D 3\n" +
            "U 1\n" +
            "D 1\n" +
            "R 1\n" +
            "D 1\n" +
            "L 6\n" +
            "U 2\n" +
            "D 4\n" +
            "U 6\n" +
            "D 4\n" +
            "L 6\n" +
            "D 4\n" +
            "R 6\n" +
            "U 4\n" +
            "R 2\n" +
            "D 2\n" +
            "U 1\n" +
            "L 2\n" +
            "U 5\n" +
            "D 4\n" +
            "L 2\n" +
            "D 1\n" +
            "L 3\n" +
            "R 1\n" +
            "L 1\n" +
            "R 6\n" +
            "L 3\n" +
            "U 5\n" +
            "D 3\n" +
            "R 5\n" +
            "U 1\n" +
            "D 5\n" +
            "R 4\n" +
            "D 2\n" +
            "U 6\n" +
            "R 1\n" +
            "U 3\n" +
            "D 2\n" +
            "R 1\n" +
            "U 6\n" +
            "R 2\n" +
            "U 5\n" +
            "R 4\n" +
            "D 6\n" +
            "U 1\n" +
            "R 2\n" +
            "D 6\n" +
            "U 5\n" +
            "R 1\n" +
            "D 6\n" +
            "U 2\n" +
            "L 3\n" +
            "U 3\n" +
            "D 1\n" +
            "R 4\n" +
            "D 1\n" +
            "L 3\n" +
            "R 4\n" +
            "U 2\n" +
            "R 6\n" +
            "L 3\n" +
            "R 6\n" +
            "U 6\n" +
            "D 1\n" +
            "R 4\n" +
            "D 2\n" +
            "U 6\n" +
            "D 3\n" +
            "R 2\n" +
            "L 1\n" +
            "D 5\n" +
            "L 6\n" +
            "R 4\n" +
            "D 3\n" +
            "R 2\n" +
            "U 2\n" +
            "R 4\n" +
            "D 1\n" +
            "U 2\n" +
            "L 6\n" +
            "D 3\n" +
            "L 3\n" +
            "D 6\n" +
            "L 4\n" +
            "U 6\n" +
            "D 2\n" +
            "R 3\n" +
            "D 7\n" +
            "L 7\n" +
            "R 4\n" +
            "D 2\n" +
            "L 1\n" +
            "R 7\n" +
            "L 7\n" +
            "U 7\n" +
            "D 3\n" +
            "R 2\n" +
            "L 4\n" +
            "D 1\n" +
            "L 2\n" +
            "U 6\n" +
            "D 6\n" +
            "R 5\n" +
            "L 5\n" +
            "U 3\n" +
            "L 5\n" +
            "R 2\n" +
            "L 5\n" +
            "U 3\n" +
            "D 6\n" +
            "L 1\n" +
            "D 3\n" +
            "L 7\n" +
            "U 1\n" +
            "R 7\n" +
            "D 1\n" +
            "R 2\n" +
            "U 5\n" +
            "L 3\n" +
            "D 2\n" +
            "L 2\n" +
            "R 2\n" +
            "U 2\n" +
            "R 1\n" +
            "L 5\n" +
            "U 2\n" +
            "D 2\n" +
            "U 1\n" +
            "R 4\n" +
            "D 4\n" +
            "L 6\n" +
            "D 3\n" +
            "U 4\n" +
            "L 3\n" +
            "D 3\n" +
            "U 2\n" +
            "L 4\n" +
            "D 2\n" +
            "R 3\n" +
            "L 6\n" +
            "R 3\n" +
            "D 6\n" +
            "U 1\n" +
            "R 3\n" +
            "U 7\n" +
            "D 5\n" +
            "L 1\n" +
            "R 7\n" +
            "L 5\n" +
            "R 1\n" +
            "D 7\n" +
            "U 4\n" +
            "L 3\n" +
            "R 4\n" +
            "D 1\n" +
            "L 5\n" +
            "D 3\n" +
            "R 6\n" +
            "U 5\n" +
            "L 5\n" +
            "R 5\n" +
            "D 5\n" +
            "U 7\n" +
            "R 1\n" +
            "D 1\n" +
            "U 5\n" +
            "D 3\n" +
            "R 2\n" +
            "U 6\n" +
            "D 5\n" +
            "U 3\n" +
            "L 3\n" +
            "R 4\n" +
            "L 8\n" +
            "U 2\n" +
            "R 1\n" +
            "U 4\n" +
            "R 5\n" +
            "L 6\n" +
            "U 4\n" +
            "R 3\n" +
            "D 2\n" +
            "U 7\n" +
            "R 7\n" +
            "D 1\n" +
            "U 1\n" +
            "L 3\n" +
            "R 4\n" +
            "U 6\n" +
            "L 8\n" +
            "D 4\n" +
            "R 5\n" +
            "D 6\n" +
            "L 1\n" +
            "R 8\n" +
            "U 2\n" +
            "L 7\n" +
            "U 5\n" +
            "R 4\n" +
            "U 1\n" +
            "D 1\n" +
            "R 8\n" +
            "L 6\n" +
            "D 6\n" +
            "R 1\n" +
            "D 1\n" +
            "U 2\n" +
            "R 1\n" +
            "L 6\n" +
            "R 5\n" +
            "U 1\n" +
            "D 1\n" +
            "L 2\n" +
            "U 7\n" +
            "R 4\n" +
            "D 6\n" +
            "L 3\n" +
            "D 7\n" +
            "U 1\n" +
            "R 7\n" +
            "D 1\n" +
            "R 6\n" +
            "L 2\n" +
            "D 4\n" +
            "L 3\n" +
            "R 7\n" +
            "L 7\n" +
            "U 8\n" +
            "R 7\n" +
            "L 5\n" +
            "D 8\n" +
            "R 1\n" +
            "D 4\n" +
            "L 3\n" +
            "R 7\n" +
            "L 4\n" +
            "U 7\n" +
            "L 3\n" +
            "D 7\n" +
            "L 4\n" +
            "R 8\n" +
            "L 5\n" +
            "D 2\n" +
            "R 3\n" +
            "U 6\n" +
            "D 1\n" +
            "L 7\n" +
            "D 1\n" +
            "U 2\n" +
            "D 8\n" +
            "U 7\n" +
            "R 1\n" +
            "U 8\n" +
            "L 4\n" +
            "U 4\n" +
            "D 5\n" +
            "R 2\n" +
            "D 7\n" +
            "R 5\n" +
            "L 4\n" +
            "D 4\n" +
            "U 4\n" +
            "D 5\n" +
            "U 2\n" +
            "D 5\n" +
            "R 8\n" +
            "D 7\n" +
            "U 2\n" +
            "D 7\n" +
            "R 3\n" +
            "U 6\n" +
            "L 6\n" +
            "D 5\n" +
            "L 5\n" +
            "R 3\n" +
            "U 5\n" +
            "R 5\n" +
            "L 3\n" +
            "D 3\n" +
            "R 3\n" +
            "D 5\n" +
            "R 6\n" +
            "D 3\n" +
            "L 1\n" +
            "U 6\n" +
            "R 4\n" +
            "D 4\n" +
            "R 8\n" +
            "D 6\n" +
            "L 8\n" +
            "D 2\n" +
            "U 1\n" +
            "L 9\n" +
            "R 8\n" +
            "D 6\n" +
            "L 8\n" +
            "R 6\n" +
            "L 8\n" +
            "U 4\n" +
            "L 6\n" +
            "R 5\n" +
            "U 1\n" +
            "L 5\n" +
            "R 8\n" +
            "D 3\n" +
            "L 8\n" +
            "R 9\n" +
            "U 9\n" +
            "L 5\n" +
            "D 5\n" +
            "R 2\n" +
            "D 1\n" +
            "U 4\n" +
            "R 1\n" +
            "U 2\n" +
            "R 2\n" +
            "L 8\n" +
            "D 1\n" +
            "L 3\n" +
            "D 2\n" +
            "U 1\n" +
            "L 8\n" +
            "R 5\n" +
            "L 2\n" +
            "D 9\n" +
            "U 4\n" +
            "L 5\n" +
            "D 3\n" +
            "U 4\n" +
            "D 8\n" +
            "L 4\n" +
            "U 1\n" +
            "L 1\n" +
            "D 2\n" +
            "U 6\n" +
            "D 8\n" +
            "U 3\n" +
            "D 2\n" +
            "U 3\n" +
            "R 5\n" +
            "U 6\n" +
            "L 1\n" +
            "U 1\n" +
            "L 8\n" +
            "D 9\n" +
            "L 4\n" +
            "U 4\n" +
            "R 3\n" +
            "D 6\n" +
            "U 5\n" +
            "L 8\n" +
            "D 4\n" +
            "U 4\n" +
            "L 8\n" +
            "R 6\n" +
            "L 4\n" +
            "U 5\n" +
            "R 5\n" +
            "U 4\n" +
            "D 4\n" +
            "U 4\n" +
            "R 7\n" +
            "L 8\n" +
            "U 6\n" +
            "L 9\n" +
            "R 8\n" +
            "U 5\n" +
            "L 2\n" +
            "U 5\n" +
            "D 3\n" +
            "L 7\n" +
            "D 4\n" +
            "R 1\n" +
            "U 3\n" +
            "R 6\n" +
            "L 9\n" +
            "R 8\n" +
            "U 8\n" +
            "L 7\n" +
            "R 1\n" +
            "L 1\n" +
            "U 3\n" +
            "D 8\n" +
            "R 3\n" +
            "D 1\n" +
            "L 5\n" +
            "D 2\n" +
            "R 4\n" +
            "U 9\n" +
            "L 1\n" +
            "R 1\n" +
            "L 5\n" +
            "R 4\n" +
            "U 8\n" +
            "D 6\n" +
            "U 6\n" +
            "R 9\n" +
            "L 3\n" +
            "R 9\n" +
            "U 1\n" +
            "R 9\n" +
            "D 5\n" +
            "L 4\n" +
            "R 6\n" +
            "L 3\n" +
            "R 2\n" +
            "U 9\n" +
            "D 8\n" +
            "R 4\n" +
            "L 6\n" +
            "R 5\n" +
            "L 6\n" +
            "U 6\n" +
            "R 8\n" +
            "U 10\n" +
            "L 2\n" +
            "R 1\n" +
            "D 8\n" +
            "L 9\n" +
            "U 4\n" +
            "D 1\n" +
            "L 9\n" +
            "R 6\n" +
            "U 7\n" +
            "D 7\n" +
            "L 6\n" +
            "R 6\n" +
            "U 2\n" +
            "L 3\n" +
            "U 6\n" +
            "R 4\n" +
            "L 10\n" +
            "R 1\n" +
            "L 5\n" +
            "U 2\n" +
            "R 6\n" +
            "D 2\n" +
            "R 9\n" +
            "L 4\n" +
            "U 4\n" +
            "D 1\n" +
            "L 7\n" +
            "R 8\n" +
            "L 1\n" +
            "D 9\n" +
            "L 6\n" +
            "U 6\n" +
            "L 10\n" +
            "U 1\n" +
            "L 2\n" +
            "R 2\n" +
            "U 3\n" +
            "L 5\n" +
            "D 4\n" +
            "L 8\n" +
            "D 7\n" +
            "L 5\n" +
            "R 3\n" +
            "D 7\n" +
            "U 10\n" +
            "D 10\n" +
            "R 8\n" +
            "D 3\n" +
            "R 7\n" +
            "D 5\n" +
            "R 10\n" +
            "D 9\n" +
            "R 6\n" +
            "L 3\n" +
            "R 1\n" +
            "U 8\n" +
            "L 3\n" +
            "R 9\n" +
            "U 4\n" +
            "D 3\n" +
            "R 8\n" +
            "D 10\n" +
            "U 5\n" +
            "D 8\n" +
            "L 3\n" +
            "D 8\n" +
            "L 3\n" +
            "D 6\n" +
            "R 6\n" +
            "D 1\n" +
            "R 3\n" +
            "D 10\n" +
            "R 4\n" +
            "L 2\n" +
            "R 10\n" +
            "D 4\n" +
            "U 1\n" +
            "L 9\n" +
            "R 9\n" +
            "D 10\n" +
            "U 4\n" +
            "D 2\n" +
            "L 5\n" +
            "R 8\n" +
            "L 2\n" +
            "R 4\n" +
            "U 5\n" +
            "D 1\n" +
            "L 3\n" +
            "U 4\n" +
            "D 7\n" +
            "L 11\n" +
            "R 2\n" +
            "L 1\n" +
            "D 3\n" +
            "R 8\n" +
            "D 5\n" +
            "U 6\n" +
            "L 11\n" +
            "D 7\n" +
            "U 3\n" +
            "R 4\n" +
            "L 6\n" +
            "U 2\n" +
            "D 1\n" +
            "R 5\n" +
            "U 9\n" +
            "L 3\n" +
            "U 4\n" +
            "R 9\n" +
            "D 11\n" +
            "R 1\n" +
            "U 8\n" +
            "L 7\n" +
            "R 6\n" +
            "D 11\n" +
            "U 8\n" +
            "R 3\n" +
            "D 8\n" +
            "U 6\n" +
            "R 8\n" +
            "U 8\n" +
            "D 9\n" +
            "U 6\n" +
            "R 7\n" +
            "U 11\n" +
            "L 10\n" +
            "U 11\n" +
            "L 10\n" +
            "U 10\n" +
            "R 11\n" +
            "U 10\n" +
            "L 10\n" +
            "R 6\n" +
            "L 11\n" +
            "D 1\n" +
            "L 5\n" +
            "D 4\n" +
            "R 1\n" +
            "L 4\n" +
            "U 2\n" +
            "D 8\n" +
            "L 10\n" +
            "R 8\n" +
            "D 10\n" +
            "L 2\n" +
            "D 5\n" +
            "L 11\n" +
            "R 6\n" +
            "L 9\n" +
            "U 3\n" +
            "L 1\n" +
            "R 11\n" +
            "L 8\n" +
            "D 5\n" +
            "U 11\n" +
            "D 10\n" +
            "R 5\n" +
            "U 9\n" +
            "L 4\n" +
            "U 5\n" +
            "R 8\n" +
            "L 8\n" +
            "U 1\n" +
            "L 11\n" +
            "U 6\n" +
            "R 6\n" +
            "D 5\n" +
            "R 5\n" +
            "L 4\n" +
            "U 2\n" +
            "L 6\n" +
            "D 3\n" +
            "L 9\n" +
            "R 6\n" +
            "U 3\n" +
            "D 11\n" +
            "R 1\n" +
            "D 11\n" +
            "U 4\n" +
            "R 9\n" +
            "D 3\n" +
            "L 7\n" +
            "D 7\n" +
            "L 11\n" +
            "D 5\n" +
            "L 5\n" +
            "D 8\n" +
            "R 10\n" +
            "U 2\n" +
            "L 6\n" +
            "U 10\n" +
            "D 10\n" +
            "R 4\n" +
            "D 6\n" +
            "U 10\n" +
            "R 3\n" +
            "U 5\n" +
            "R 4\n" +
            "U 3\n" +
            "D 11\n" +
            "R 7\n" +
            "D 10\n" +
            "L 6\n" +
            "U 2\n" +
            "L 11\n" +
            "D 12\n" +
            "L 8\n" +
            "U 11\n" +
            "D 10\n" +
            "L 2\n" +
            "D 10\n" +
            "L 2\n" +
            "R 3\n" +
            "D 6\n" +
            "L 9\n" +
            "D 9\n" +
            "U 2\n" +
            "L 5\n" +
            "R 3\n" +
            "U 3\n" +
            "D 1\n" +
            "U 7\n" +
            "L 5\n" +
            "R 2\n" +
            "U 7\n" +
            "D 12\n" +
            "U 5\n" +
            "L 1\n" +
            "R 3\n" +
            "D 8\n" +
            "U 3\n" +
            "D 12\n" +
            "R 5\n" +
            "L 11\n" +
            "U 5\n" +
            "L 2\n" +
            "R 3\n" +
            "L 7\n" +
            "R 9\n" +
            "U 5\n" +
            "D 3\n" +
            "L 4\n" +
            "D 8\n" +
            "U 6\n" +
            "R 11\n" +
            "D 10\n" +
            "U 3\n" +
            "R 4\n" +
            "L 3\n" +
            "R 9\n" +
            "U 7\n" +
            "D 5\n" +
            "L 10\n" +
            "R 1\n" +
            "U 8\n" +
            "D 9\n" +
            "L 12\n" +
            "R 6\n" +
            "D 11\n" +
            "U 7\n" +
            "D 11\n" +
            "R 2\n" +
            "D 9\n" +
            "R 11\n" +
            "U 12\n" +
            "R 2\n" +
            "D 11\n" +
            "R 5\n" +
            "L 1\n" +
            "U 6\n" +
            "D 4\n" +
            "L 7\n" +
            "U 10\n" +
            "L 5\n" +
            "D 8\n" +
            "R 7\n" +
            "L 7\n" +
            "R 6\n" +
            "U 7\n" +
            "L 9\n" +
            "U 12\n" +
            "L 9\n" +
            "U 2\n" +
            "R 6\n" +
            "U 11\n" +
            "L 2\n" +
            "D 3\n" +
            "R 3\n" +
            "U 3\n" +
            "R 8\n" +
            "D 5\n" +
            "R 10\n" +
            "D 12\n" +
            "R 1\n" +
            "D 3\n" +
            "U 8\n" +
            "D 2\n" +
            "L 4\n" +
            "U 7\n" +
            "R 1\n" +
            "L 11\n" +
            "R 7\n" +
            "U 11\n" +
            "D 3\n" +
            "R 9\n" +
            "L 1\n" +
            "D 1\n" +
            "R 11\n" +
            "L 12\n" +
            "R 1\n" +
            "U 11\n" +
            "R 9\n" +
            "L 12\n" +
            "R 5\n" +
            "D 11\n" +
            "R 10\n" +
            "U 3\n" +
            "L 13\n" +
            "U 11\n" +
            "L 11\n" +
            "R 3\n" +
            "L 1\n" +
            "U 12\n" +
            "L 7\n" +
            "U 2\n" +
            "D 7\n" +
            "U 9\n" +
            "R 2\n" +
            "U 7\n" +
            "L 10\n" +
            "R 9\n" +
            "U 13\n" +
            "D 8\n" +
            "R 7\n" +
            "D 7\n" +
            "L 1\n" +
            "U 2\n" +
            "L 9\n" +
            "D 9\n" +
            "L 13\n" +
            "R 13\n" +
            "L 12\n" +
            "U 3\n" +
            "L 1\n" +
            "R 5\n" +
            "D 8\n" +
            "U 2\n" +
            "D 12\n" +
            "R 9\n" +
            "D 11\n" +
            "R 12\n" +
            "L 10\n" +
            "U 9\n" +
            "R 1\n" +
            "U 11\n" +
            "L 5\n" +
            "R 10\n" +
            "L 7\n" +
            "R 9\n" +
            "U 11\n" +
            "D 3\n" +
            "R 13\n" +
            "L 11\n" +
            "U 4\n" +
            "R 1\n" +
            "U 7\n" +
            "L 2\n" +
            "R 3\n" +
            "L 6\n" +
            "D 4\n" +
            "R 8\n" +
            "L 8\n" +
            "U 10\n" +
            "D 12\n" +
            "U 9\n" +
            "R 7\n" +
            "D 1\n" +
            "R 8\n" +
            "U 7\n" +
            "R 1\n" +
            "D 8\n" +
            "L 6\n" +
            "D 13\n" +
            "L 6\n" +
            "R 4\n" +
            "U 13\n" +
            "L 2\n" +
            "R 5\n" +
            "D 2\n" +
            "U 1\n" +
            "L 6\n" +
            "R 7\n" +
            "D 11\n" +
            "L 9\n" +
            "R 11\n" +
            "U 3\n" +
            "L 8\n" +
            "R 6\n" +
            "L 10\n" +
            "U 9\n" +
            "R 1\n" +
            "U 3\n" +
            "R 1\n" +
            "L 6\n" +
            "R 4\n" +
            "L 3\n" +
            "D 8\n" +
            "U 3\n" +
            "D 3\n" +
            "U 8\n" +
            "L 12\n" +
            "R 5\n" +
            "L 3\n" +
            "D 8\n" +
            "L 7\n" +
            "D 3\n" +
            "R 5\n" +
            "L 3\n" +
            "R 11\n" +
            "L 4\n" +
            "U 6\n" +
            "R 7\n" +
            "L 11\n" +
            "D 4\n" +
            "R 5\n" +
            "U 6\n" +
            "R 13\n" +
            "D 11\n" +
            "U 2\n" +
            "D 12\n" +
            "L 8\n" +
            "R 3\n" +
            "D 4\n" +
            "L 12\n" +
            "D 7\n" +
            "R 14\n" +
            "U 8\n" +
            "R 12\n" +
            "U 14\n" +
            "R 1\n" +
            "L 3\n" +
            "R 13\n" +
            "U 14\n" +
            "D 12\n" +
            "R 4\n" +
            "U 4\n" +
            "R 14\n" +
            "D 10\n" +
            "U 11\n" +
            "R 10\n" +
            "D 13\n" +
            "U 8\n" +
            "R 13\n" +
            "L 9\n" +
            "U 6\n" +
            "D 7\n" +
            "U 9\n" +
            "L 11\n" +
            "U 10\n" +
            "L 14\n" +
            "U 7\n" +
            "L 5\n" +
            "D 1\n" +
            "U 8\n" +
            "R 14\n" +
            "U 12\n" +
            "L 1\n" +
            "R 4\n" +
            "L 7\n" +
            "D 2\n" +
            "R 5\n" +
            "D 3\n" +
            "R 14\n" +
            "U 6\n" +
            "D 7\n" +
            "R 2\n" +
            "L 8\n" +
            "U 14\n" +
            "D 12\n" +
            "U 12\n" +
            "L 5\n" +
            "D 5\n" +
            "L 1\n" +
            "U 3\n" +
            "L 10\n" +
            "R 4\n" +
            "U 2\n" +
            "R 11\n" +
            "D 6\n" +
            "U 12\n" +
            "D 5\n" +
            "U 11\n" +
            "D 5\n" +
            "L 8\n" +
            "D 1\n" +
            "L 7\n" +
            "D 1\n" +
            "U 9\n" +
            "D 6\n" +
            "L 10\n" +
            "D 7\n" +
            "L 10\n" +
            "R 7\n" +
            "D 11\n" +
            "L 9\n" +
            "U 13\n" +
            "D 10\n" +
            "U 10\n" +
            "R 13\n" +
            "L 2\n" +
            "R 13\n" +
            "U 3\n" +
            "R 8\n" +
            "D 7\n" +
            "L 2\n" +
            "U 1\n" +
            "L 7\n" +
            "D 11\n" +
            "U 6\n" +
            "D 12\n" +
            "L 3\n" +
            "R 3\n" +
            "D 1\n" +
            "R 2\n" +
            "D 2\n" +
            "U 4\n" +
            "D 1\n" +
            "L 12\n" +
            "U 5\n" +
            "L 3\n" +
            "R 13\n" +
            "D 9\n" +
            "L 3\n" +
            "D 10\n" +
            "L 5\n" +
            "R 13\n" +
            "D 9\n" +
            "L 7\n" +
            "R 12\n" +
            "L 8\n" +
            "U 1\n" +
            "R 5\n" +
            "L 3\n" +
            "D 7\n" +
            "R 4\n" +
            "U 6\n" +
            "R 4\n" +
            "U 15\n" +
            "D 13\n" +
            "R 3\n" +
            "L 14\n" +
            "R 1\n" +
            "U 3\n" +
            "R 4\n" +
            "U 12\n" +
            "R 7\n" +
            "D 7\n" +
            "U 1\n" +
            "R 12\n" +
            "D 9\n" +
            "R 14\n" +
            "U 10\n" +
            "R 1\n" +
            "U 6\n" +
            "D 10\n" +
            "R 14\n" +
            "D 12\n" +
            "R 6\n" +
            "D 13\n" +
            "U 14\n" +
            "R 15\n" +
            "U 9\n" +
            "L 6\n" +
            "R 7\n" +
            "L 13\n" +
            "R 4\n" +
            "D 8\n" +
            "R 2\n" +
            "L 6\n" +
            "U 13\n" +
            "L 15\n" +
            "D 5\n" +
            "U 4\n" +
            "R 14\n" +
            "D 5\n" +
            "L 6\n" +
            "U 3\n" +
            "R 10\n" +
            "L 12\n" +
            "U 9\n" +
            "D 5\n" +
            "L 4\n" +
            "U 1\n" +
            "R 10\n" +
            "L 3\n" +
            "U 5\n" +
            "R 12\n" +
            "D 14\n" +
            "L 10\n" +
            "R 9\n" +
            "D 2\n" +
            "U 6\n" +
            "D 6\n" +
            "U 1\n" +
            "L 8\n" +
            "R 3\n" +
            "D 8\n" +
            "R 1\n" +
            "D 5\n" +
            "L 10\n" +
            "D 11\n" +
            "L 5\n" +
            "R 6\n" +
            "D 8\n" +
            "R 2\n" +
            "D 12\n" +
            "L 7\n" +
            "R 14\n" +
            "D 8\n" +
            "L 8\n" +
            "U 14\n" +
            "R 13\n" +
            "L 7\n" +
            "D 8\n" +
            "U 3\n" +
            "L 6\n" +
            "U 6\n" +
            "D 4\n" +
            "R 9\n" +
            "L 11\n" +
            "R 2\n" +
            "U 10\n" +
            "R 14\n" +
            "D 8\n" +
            "R 2\n" +
            "U 10\n" +
            "R 7\n" +
            "U 3\n" +
            "R 4\n" +
            "D 9\n" +
            "U 9\n" +
            "D 11\n" +
            "U 5\n" +
            "D 9\n" +
            "R 14\n" +
            "U 13\n" +
            "D 5\n" +
            "L 7\n" +
            "R 2\n" +
            "D 9\n" +
            "R 2\n" +
            "U 9\n" +
            "D 8\n" +
            "L 12\n" +
            "R 12\n" +
            "L 3\n" +
            "R 6\n" +
            "U 16\n" +
            "R 15\n" +
            "D 8\n" +
            "U 3\n" +
            "R 1\n" +
            "L 8\n" +
            "D 11\n" +
            "L 6\n" +
            "R 5\n" +
            "L 14\n" +
            "D 15\n" +
            "U 1\n" +
            "R 10\n" +
            "D 11\n" +
            "R 16\n" +
            "D 1\n" +
            "U 6\n" +
            "L 12\n" +
            "U 3\n" +
            "D 9\n" +
            "U 1\n" +
            "D 13\n" +
            "L 14\n" +
            "R 8\n" +
            "L 9\n" +
            "D 3\n" +
            "U 16\n" +
            "R 3\n" +
            "L 11\n" +
            "R 13\n" +
            "L 10\n" +
            "U 10\n" +
            "L 3\n" +
            "R 7\n" +
            "L 6\n" +
            "R 2\n" +
            "D 4\n" +
            "U 15\n" +
            "R 13\n" +
            "U 10\n" +
            "D 1\n" +
            "L 3\n" +
            "D 15\n" +
            "L 9\n" +
            "R 8\n" +
            "D 14\n" +
            "R 11\n" +
            "L 11\n" +
            "D 4\n" +
            "U 15\n" +
            "L 2\n" +
            "U 4\n" +
            "D 3\n" +
            "U 6\n" +
            "D 5\n" +
            "U 15\n" +
            "L 8\n" +
            "D 14\n" +
            "R 1\n" +
            "U 8\n" +
            "L 7\n" +
            "D 8\n" +
            "R 8\n" +
            "U 1\n" +
            "D 8\n" +
            "R 11\n" +
            "D 4\n" +
            "U 14\n" +
            "R 11\n" +
            "D 16\n" +
            "U 4\n" +
            "D 9\n" +
            "R 11\n" +
            "L 16\n" +
            "D 5\n" +
            "L 9\n" +
            "R 6\n" +
            "U 9\n" +
            "D 16\n" +
            "R 4\n" +
            "L 11\n" +
            "U 11\n" +
            "D 6\n" +
            "U 13\n" +
            "D 14\n" +
            "U 13\n" +
            "L 8\n" +
            "U 9\n" +
            "D 3\n" +
            "R 4\n" +
            "L 8\n" +
            "D 7\n" +
            "L 12\n" +
            "D 6\n" +
            "R 14\n" +
            "L 11\n" +
            "U 7\n" +
            "D 4\n" +
            "U 1\n" +
            "L 11\n" +
            "U 15\n" +
            "L 5\n" +
            "D 8\n" +
            "U 2\n" +
            "R 15\n" +
            "L 5\n" +
            "R 7\n" +
            "L 8\n" +
            "R 15\n" +
            "U 8\n" +
            "D 7\n" +
            "U 17\n" +
            "D 5\n" +
            "U 15\n" +
            "R 8\n" +
            "U 15\n" +
            "L 7\n" +
            "U 5\n" +
            "D 11\n" +
            "L 4\n" +
            "U 11\n" +
            "D 13\n" +
            "R 10\n" +
            "D 12\n" +
            "L 16\n" +
            "D 9\n" +
            "L 17\n" +
            "U 1\n" +
            "R 10\n" +
            "D 1\n" +
            "R 16\n" +
            "U 6\n" +
            "L 2\n" +
            "D 7\n" +
            "U 8\n" +
            "D 12\n" +
            "L 15\n" +
            "U 16\n" +
            "R 5\n" +
            "L 13\n" +
            "D 2\n" +
            "U 7\n" +
            "L 14\n" +
            "D 6\n" +
            "L 8\n" +
            "R 12\n" +
            "U 4\n" +
            "D 7\n" +
            "U 4\n" +
            "R 3\n" +
            "U 8\n" +
            "D 5\n" +
            "L 4\n" +
            "U 3\n" +
            "R 13\n" +
            "L 14\n" +
            "R 7\n" +
            "U 11\n" +
            "D 9\n" +
            "R 1\n" +
            "D 15\n" +
            "R 11\n" +
            "L 8\n" +
            "R 7\n" +
            "D 17\n" +
            "U 13\n" +
            "R 15\n" +
            "D 5\n" +
            "R 15\n" +
            "U 7\n" +
            "R 10\n" +
            "U 14\n" +
            "D 2\n" +
            "L 7\n" +
            "R 13\n" +
            "D 10\n" +
            "U 16\n" +
            "D 6\n" +
            "R 10\n" +
            "D 4\n" +
            "U 1\n" +
            "R 14\n" +
            "U 2\n" +
            "L 2\n" +
            "U 1\n" +
            "L 13\n" +
            "D 2\n" +
            "U 16\n" +
            "D 1\n" +
            "U 8\n" +
            "L 7\n" +
            "U 17\n" +
            "D 9\n" +
            "L 10\n" +
            "U 16\n" +
            "D 13\n" +
            "U 15\n" +
            "D 12\n" +
            "L 6\n" +
            "D 9\n" +
            "L 3\n" +
            "R 17\n" +
            "U 16\n" +
            "L 6\n" +
            "D 11\n" +
            "R 11\n" +
            "L 11\n" +
            "U 2\n" +
            "R 15\n" +
            "D 11\n" +
            "R 10\n" +
            "U 2\n" +
            "D 18\n" +
            "U 18\n" +
            "D 18\n" +
            "L 4\n" +
            "U 1\n" +
            "R 1\n" +
            "L 7\n" +
            "U 7\n" +
            "L 12\n" +
            "U 10\n" +
            "R 13\n" +
            "D 16\n" +
            "R 1\n" +
            "D 11\n" +
            "L 12\n" +
            "R 7\n" +
            "D 13\n" +
            "L 10\n" +
            "D 6\n" +
            "U 1\n" +
            "L 14\n" +
            "R 13\n" +
            "D 14\n" +
            "L 3\n" +
            "D 18\n" +
            "L 2\n" +
            "U 9\n" +
            "L 7\n" +
            "R 18\n" +
            "L 11\n" +
            "U 16\n" +
            "R 9\n" +
            "U 8\n" +
            "D 5\n" +
            "L 15\n" +
            "R 16\n" +
            "D 17\n" +
            "U 16\n" +
            "L 10\n" +
            "U 4\n" +
            "R 1\n" +
            "L 10\n" +
            "U 4\n" +
            "L 8\n" +
            "U 5\n" +
            "L 5\n" +
            "R 18\n" +
            "U 11\n" +
            "R 18\n" +
            "U 12\n" +
            "D 18\n" +
            "R 9\n" +
            "L 2\n" +
            "D 10\n" +
            "L 15\n" +
            "D 2\n" +
            "R 7\n" +
            "D 16\n" +
            "L 4\n" +
            "R 13\n" +
            "L 4\n" +
            "R 2\n" +
            "L 14\n" +
            "D 4\n" +
            "R 15\n" +
            "D 14\n" +
            "R 13\n" +
            "L 9\n" +
            "D 1\n" +
            "U 7\n" +
            "R 17\n" +
            "L 6\n" +
            "U 1\n" +
            "L 6\n" +
            "D 6\n" +
            "U 5\n" +
            "L 5\n" +
            "R 10\n" +
            "U 1\n" +
            "R 9\n" +
            "U 3\n" +
            "D 2\n" +
            "L 4\n" +
            "U 1\n" +
            "D 12\n" +
            "R 5\n" +
            "U 3\n" +
            "R 15\n" +
            "L 18\n" +
            "R 3\n" +
            "D 1\n" +
            "L 6\n" +
            "D 16\n" +
            "U 15\n" +
            "D 6\n" +
            "R 8\n" +
            "D 4\n" +
            "R 14\n" +
            "U 10\n" +
            "R 10\n" +
            "D 5\n" +
            "L 14\n" +
            "U 6\n" +
            "L 15\n" +
            "R 10\n" +
            "D 17\n" +
            "R 7\n" +
            "L 13\n" +
            "R 12\n" +
            "D 4\n" +
            "R 11\n" +
            "D 2\n" +
            "L 1\n" +
            "R 13\n" +
            "U 6\n" +
            "D 16\n" +
            "R 5\n" +
            "D 17\n" +
            "U 17\n" +
            "D 11\n" +
            "R 15\n" +
            "L 4\n" +
            "D 13\n" +
            "L 11\n" +
            "U 16\n" +
            "L 3\n" +
            "D 5\n" +
            "U 1\n" +
            "R 16\n" +
            "L 10\n" +
            "U 7\n" +
            "D 9\n" +
            "R 10\n" +
            "L 4\n" +
            "D 4\n" +
            "L 7\n" +
            "D 12\n" +
            "U 5\n" +
            "D 10\n" +
            "R 2\n" +
            "L 9\n" +
            "D 6\n" +
            "U 14\n" +
            "R 4\n" +
            "U 2\n" +
            "L 19\n" +
            "R 15\n" +
            "L 13\n" +
            "R 12\n" +
            "L 8\n" +
            "D 15\n" +
            "U 13\n" +
            "L 4\n" +
            "U 13\n" +
            "D 3\n" +
            "U 7\n" +
            "L 10\n" +
            "R 8\n" +
            "D 14\n" +
            "R 3\n" +
            "L 10\n" +
            "D 3\n" +
            "U 5\n" +
            "L 15\n" +
            "R 5\n" +
            "L 2\n" +
            "R 10\n" +
            "D 5\n" +
            "R 13\n" +
            "L 18\n" +
            "R 7\n" +
            "L 6\n" +
            "U 12\n" +
            "D 16\n" +
            "R 3\n" +
            "L 11\n" +
            "D 7\n" +
            "R 1\n" +
            "U 9\n" +
            "R 9\n" +
            "D 6\n" +
            "L 1\n" +
            "D 13\n" +
            "U 10\n" +
            "L 17\n" +
            "R 10\n" +
            "L 12\n" +
            "R 8\n" +
            "D 10\n" +
            "R 12\n" +
            "U 12\n" +
            "D 14\n" +
            "U 1\n" +
            "D 4\n" +
            "U 2\n" +
            "L 9\n" +
            "R 3\n" +
            "U 2\n" +
            "R 19\n" +
            "D 1\n" +
            "L 4\n" +
            "R 6\n" +
            "L 4\n" +
            "D 4\n" +
            "R 16\n" +
            "D 17\n" +
            "R 3\n" +
            "D 9\n" +
            "L 8\n" +
            "R 15\n" +
            "D 4\n" +
            "U 13\n" +
            "D 4\n" +
            "U 17\n" +
            "D 15\n" +
            "L 17\n" +
            "D 1\n" +
            "R 14\n" +
            "L 18\n" +
            "U 2\n" +
            "R 11\n" +
            "U 5\n").split("\n"));
}
