package nl.jiankai;

import java.util.Arrays;
import java.util.List;

public class Day2 {
    static final List<String> passwordWithRules = Arrays.asList(("13-16 k: kkkkkgmkbvkkrskhd\n" +
            "5-6 p: qpppvzp\n" +
            "3-4 p: psppxhlfpvkh\n" +
            "3-10 w: wwwwwwwwwwdwww\n" +
            "4-5 r: rcgrrcr\n" +
            "3-4 c: clvccc\n" +
            "1-5 x: xfsfxmctb\n" +
            "9-14 k: kpkmkkckhkkkkvkk\n" +
            "5-6 s: gsfsss\n" +
            "4-8 c: cccdcqdcr\n" +
            "2-5 k: kmkpkkfgkkkkdkkk\n" +
            "9-11 f: pfnsfffwxsn\n" +
            "8-9 w: wjwnwcwxc\n" +
            "7-8 q: rrxhplqs\n" +
            "5-10 n: gpnkqnxnbjzgjnb\n" +
            "18-19 p: fvpkgfkfjgwllqwhrjd\n" +
            "12-13 v: kvvvbmdvvvvvvcvvvv\n" +
            "3-5 m: mdmkmvhszpjcxl\n" +
            "2-7 v: qjmvzdwxc\n" +
            "1-4 b: bbbbbbbb\n" +
            "2-5 c: fzcdccfkcsjhckccrcx\n" +
            "2-10 d: fhdwdbdddrsldrtdjdr\n" +
            "1-7 z: ztszzfzztcqzrz\n" +
            "4-6 j: mmjjjrj\n" +
            "11-12 b: smbgkbbmbpbbmkbbbb\n" +
            "3-5 r: jxzrk\n" +
            "13-15 d: fppsvgqrdgrbddd\n" +
            "12-14 w: wwwwkcwwwpwzwzwwsz\n" +
            "5-6 v: lmcvvv\n" +
            "12-14 x: xxxxxxvxxmxbjnx\n" +
            "1-2 p: hpgpt\n" +
            "10-11 k: qmktzklkgkcknfwkh\n" +
            "6-7 r: ntcrrrjrznk\n" +
            "7-8 v: vshxvzxw\n" +
            "9-13 c: cncccccclcdwccwmc\n" +
            "5-6 r: srrrgv\n" +
            "6-9 w: bwfswqthk\n" +
            "5-7 f: hfvsfjf\n" +
            "11-14 v: zbksgqcrclvvwpfvfr\n" +
            "8-9 v: vvvvvmvvvkv\n" +
            "1-12 n: gnnnnnnndnqnd\n" +
            "10-11 j: jtjjjvbjjhj\n" +
            "3-10 x: vgxxxwqxkxn\n" +
            "5-6 z: zzzztr\n" +
            "2-4 z: rzdhz\n" +
            "10-11 m: mmmmmmmmmmvj\n" +
            "2-4 z: jzczpvzzs\n" +
            "1-4 k: rkkhk\n" +
            "4-8 n: nwcwmnflpbnnl\n" +
            "2-4 w: dwwgwwssf\n" +
            "1-3 m: smzm\n" +
            "2-6 d: dsddwwljd\n" +
            "13-15 w: wwwwrwwwdvwwpwg\n" +
            "7-10 f: bhsfffzfjdbfmf\n" +
            "6-7 w: wwwwtwww\n" +
            "3-6 b: bbbbbbxb\n" +
            "7-9 d: dvwdxjgdhf\n" +
            "12-14 n: znnnnnnnnlnfnrn\n" +
            "1-7 v: qvkvvvgv\n" +
            "2-15 x: xsxxxxxxxxxxxxbx\n" +
            "5-11 n: nckpwnmmnzg\n" +
            "4-13 d: dzdddcdkxgqddqdp\n" +
            "5-17 m: mkxmzbmmmmvfvmmjvmmm\n" +
            "11-13 p: pppzppppswhqhpppp\n" +
            "4-5 b: bbbgg\n" +
            "5-8 v: vvvvvvsv\n" +
            "9-10 j: jnlkmhmvjvnbjcsvlwb\n" +
            "2-4 x: zxxxxv\n" +
            "1-17 r: drrrrrrrrrrrrrrrcr\n" +
            "11-17 w: wqmwlszsnnwwwzwwwww\n" +
            "2-3 m: mmmmmmmmm\n" +
            "9-10 n: nrnngngnvr\n" +
            "4-8 z: bxjtzkdzwkzz\n" +
            "5-8 g: vjtvqtgqjgtggggmj\n" +
            "2-5 q: qfgcqw\n" +
            "6-11 c: cgccccchcccvc\n" +
            "6-8 t: tpjgfjpr\n" +
            "5-10 h: hhhnhbhhczhh\n" +
            "11-14 d: gdddddddddwdddr\n" +
            "1-2 l: twngrmgrckmlmh\n" +
            "10-12 r: rrrrrrfprfrr\n" +
            "7-8 m: bmmmmsrhqm\n" +
            "2-11 w: wlwwwwdnqsvw\n" +
            "10-13 j: jjjjjjtjzjjjj\n" +
            "4-16 f: fdvgffxfzcffffff\n" +
            "2-6 q: wbfvkm\n" +
            "4-6 d: ddddddd\n" +
            "2-4 p: jpxprdpn\n" +
            "5-6 s: tgssrrpbvsgs\n" +
            "3-10 j: spjgjjjcbjsjxj\n" +
            "5-10 w: wwqrdvwwwpwwwr\n" +
            "3-4 x: hpxxxzf\n" +
            "4-8 d: dxcpddddddrddddddqj\n" +
            "15-16 z: zhfxlzzkzzgzhzzz\n" +
            "3-5 s: ssslsnc\n" +
            "2-3 j: rrjrwg\n" +
            "7-13 x: xxxxxxpxxxxxtxx\n" +
            "5-8 x: xxxxxxxrxxxxxxxgx\n" +
            "4-10 g: dmhcmbwnwwggcw\n" +
            "6-8 s: qtsxflsfshzvsgpxg\n" +
            "7-9 c: cbvccckcwc\n" +
            "15-16 r: rlrrrrrrnrrrrrsx\n" +
            "8-10 r: kjrbrrrbrnvrrx\n" +
            "6-7 q: zpsmcjmmr\n" +
            "5-10 p: ppgpsppppkpp\n" +
            "3-4 k: kbkkk\n" +
            "1-2 b: bbbbb\n" +
            "8-11 s: sssvssssbsw\n" +
            "5-7 m: lmwrmmmmgmfhd\n" +
            "16-18 j: jjjjjjjjjjjjjljsjt\n" +
            "1-14 b: bcjlbbcwbjbxbbvbf\n" +
            "2-5 z: qzzrfv\n" +
            "4-17 t: tttrtzttttttttttxttt\n" +
            "5-6 w: kwwwjw\n" +
            "7-9 l: bclgtbghdtd\n" +
            "1-8 h: mqhbhhhhhhh\n" +
            "5-6 j: zznjjfvvjwcths\n" +
            "5-7 t: tttbmttd\n" +
            "5-14 v: vvvvpjvvvvvvhm\n" +
            "2-4 x: vxlx\n" +
            "5-15 g: gfgfnnqkbgngpdpp\n" +
            "1-8 n: jnnnnpnvntrp\n" +
            "3-4 b: bbbb\n" +
            "6-7 z: frszzzfz\n" +
            "6-9 f: pbbmlvfpwvw\n" +
            "4-15 g: gbjgggfgvggggdgbq\n" +
            "1-9 w: tgwljtgwlm\n" +
            "14-15 k: kkkkkkkkkkkkkzk\n" +
            "11-12 p: ppppppppppklp\n" +
            "4-8 n: nnnvpkzsn\n" +
            "13-16 m: fmjsqwtmwbdxmnwmlmb\n" +
            "2-7 c: qccgccczcc\n" +
            "8-11 x: xxxxkxxbxxx\n" +
            "1-4 g: gcgb\n" +
            "6-7 l: pkjllll\n" +
            "2-3 n: mnntpwsrlqkxkgnlb\n" +
            "9-10 s: sssssssscss\n" +
            "6-16 n: rtthnbsrfvndnsnnj\n" +
            "1-2 h: hjdhh\n" +
            "1-3 f: ffff\n" +
            "6-9 l: xqtvlllllpmlxtl\n" +
            "6-11 r: rrrrrrrrrrr\n" +
            "1-6 z: fzzzzzzzzzz\n" +
            "2-7 q: qqdqqqgqqqqtxqqqq\n" +
            "9-13 k: dbfkszjjmkkkfkdkklxk\n" +
            "5-6 j: mdjjljdfzjvqd\n" +
            "5-10 s: tsbskgsbtsqdd\n" +
            "12-14 j: tjjsjdjfjtjjfjj\n" +
            "9-10 x: xxxxxxxxgx\n" +
            "8-11 r: rrgrrrrbrrcrrr\n" +
            "6-18 m: vmnmhmbmmmmmmmmmmz\n" +
            "6-8 k: llkkqrkc\n" +
            "1-2 c: cccc\n" +
            "2-8 x: xxxxxxxxxx\n" +
            "7-10 p: ppzppppppwp\n" +
            "9-17 v: cdjwncwrbcgkfvwzvkf\n" +
            "6-11 w: wwftwjwwwcwwvwwvw\n" +
            "12-16 g: gggggggggxggggggggh\n" +
            "1-4 z: kzxzcdnpgczhn\n" +
            "3-5 t: tttmtttvxtd\n" +
            "4-5 h: hhhwh\n" +
            "4-8 d: dvddddln\n" +
            "8-15 l: lvllfllllxllllwmpl\n" +
            "7-9 s: dbsksbwtj\n" +
            "8-15 q: qkbqmqqqqqqqccqhq\n" +
            "2-6 r: grcsrrqz\n" +
            "14-18 s: sssssssssssssssssss\n" +
            "7-10 r: ffrrttnrrrrs\n" +
            "2-11 c: csccccccfdgccgcccccc\n" +
            "3-5 r: rrrrr\n" +
            "3-4 h: qrhh\n" +
            "7-9 k: kkzqkrkwk\n" +
            "1-5 k: khkkfgkj\n" +
            "3-6 l: pplnxl\n" +
            "10-13 k: chsxfrtrkkjgq\n" +
            "6-9 b: lbbblnbrbbb\n" +
            "3-5 n: hqnlfpnj\n" +
            "5-8 f: shffkcnfdmswfrnsfrpg\n" +
            "2-7 j: jjjjcdcnwxnbr\n" +
            "4-13 z: dvxnzpcbfkngk\n" +
            "11-13 h: hwzpzbphjhrhk\n" +
            "1-10 v: vqptqpbbtq\n" +
            "1-4 b: bdfpt\n" +
            "13-18 p: pppppppppppppppppp\n" +
            "14-15 h: hhhfhhhhhhhhhnmhh\n" +
            "4-14 x: wxsbxxxjvxxbxx\n" +
            "9-10 m: mmdmmxsrjdmpdmzsmm\n" +
            "11-16 s: szsbssssssszsxss\n" +
            "9-13 h: hhhhbhvhthhvnh\n" +
            "5-6 q: qqqqqq\n" +
            "1-3 d: ddldcqrdmd\n" +
            "11-17 f: ffcfkfffffpwfqffm\n" +
            "3-6 m: rmmmqm\n" +
            "9-11 l: vlblgszllwbvpn\n" +
            "13-15 z: ghzvdlzrvrzzcnz\n" +
            "3-5 l: bglllcll\n" +
            "1-8 h: hhhhhhhhhh\n" +
            "2-7 j: qjsgtjjt\n" +
            "1-2 d: ddbctlvpdf\n" +
            "11-14 v: vvvbvvvvvvtvvvvv\n" +
            "14-15 g: ggzgggggggswgrjggm\n" +
            "9-13 v: hqtcqvnbvqnmv\n" +
            "12-13 b: bbbbbbbbbbbjzbbbbb\n" +
            "5-6 r: rrfrcv\n" +
            "4-6 p: pppppppppppp\n" +
            "6-12 d: fdddddddddddrd\n" +
            "12-17 g: ggghgggggggxggggfgp\n" +
            "2-7 h: hqhhhhjhh\n" +
            "8-12 v: vvvlvvvvvvvv\n" +
            "4-5 n: nnkpg\n" +
            "3-12 m: mmzmmmmmmmmmmmm\n" +
            "11-14 b: bbbbbpbbbbbbdbbbb\n" +
            "6-7 z: zzzzzzr\n" +
            "4-7 n: snnnnfnkn\n" +
            "1-2 h: hnshhqvmjpghntx\n" +
            "15-16 b: bbbbbbbbbbbrbbbb\n" +
            "4-6 n: nxnnpnnnh\n" +
            "2-9 v: sdghvmxtkz\n" +
            "5-7 j: jjjjjjj\n" +
            "4-10 l: plbhsmlllrl\n" +
            "12-18 g: ggtggdlghcjwqwggggg\n" +
            "5-7 b: bzbxrbxgwcdbb\n" +
            "5-15 m: mmmmmmmmmmmmmmmmm\n" +
            "4-13 j: jjjjjjjjjjjjjjj\n" +
            "4-11 k: kshkkwlkkkkkdkbk\n" +
            "1-15 w: bwwwzbwwwnwwwmcww\n" +
            "19-20 l: pblvxmgslllnnsplldnv\n" +
            "3-4 z: skzx\n" +
            "1-5 x: xxqdxgb\n" +
            "2-3 g: wgggc\n" +
            "5-9 d: dgcddwrdf\n" +
            "3-6 m: mfkzjg\n" +
            "5-8 s: hmssmgwxhssg\n" +
            "10-11 s: ssssshqssll\n" +
            "17-19 v: vvsvfvvvvxvvvgvvvbv\n" +
            "11-12 t: cwssdtfqkdttjv\n" +
            "1-5 b: hcptprhlpbwkg\n" +
            "2-8 j: ljjxjjjljp\n" +
            "2-5 q: qqqlqr\n" +
            "2-8 r: jrcwdbhrcltrnsgswpm\n" +
            "3-4 f: ffvff\n" +
            "5-10 h: hhhhhhhhhhzph\n" +
            "5-6 z: mzzmctzz\n" +
            "10-13 w: wwwwwjwqwwwwwwwwww\n" +
            "1-4 m: mmtm\n" +
            "11-12 z: tddzcrptcnlmbjj\n" +
            "3-6 l: llmllpl\n" +
            "2-4 f: ffsf\n" +
            "5-11 g: gggrvgggggg\n" +
            "2-10 k: zbmpktfnddfs\n" +
            "5-9 l: lsbblgpjlms\n" +
            "1-12 s: sssssssssssss\n" +
            "5-7 f: fffdrsc\n" +
            "9-11 z: rzzzzkfzzwqzrz\n" +
            "3-6 z: zwzrbzv\n" +
            "17-18 r: rrrrrrrrrrrrrrrrrg\n" +
            "2-4 n: nnnrgnnn\n" +
            "3-4 n: nfqq\n" +
            "2-3 h: khhc\n" +
            "9-10 x: xxxffbxxxnr\n" +
            "5-6 d: mtgnrjdnmzhddks\n" +
            "3-4 b: bbbb\n" +
            "11-15 p: kppxppppppppppppp\n" +
            "13-18 t: tttdtttttttttttttttt\n" +
            "1-7 p: frjpppwgdpzvvfwds\n" +
            "1-6 k: qkzkkvpk\n" +
            "4-15 n: nnnxnnnnnnnnnnpqn\n" +
            "6-7 l: ndlrqrl\n" +
            "4-5 r: rchrwr\n" +
            "11-12 f: ffffffffhfff\n" +
            "1-3 j: xjjjj\n" +
            "9-10 z: zzzzlzzzgn\n" +
            "6-17 g: tgrhpggcqbjwjggmgql\n" +
            "11-15 v: vvvvvvvvvvlvvvhv\n" +
            "10-13 w: wwwwwwwtwwwwswwfwww\n" +
            "1-2 l: plllllllllllpll\n" +
            "8-9 k: kkckklwkc\n" +
            "2-4 b: bvbp\n" +
            "1-6 r: rrrnqrrrrrrrrrrrrr\n" +
            "8-10 d: pwnvkxddpddd\n" +
            "3-6 k: kkkwkf\n" +
            "8-15 v: vvvvvvvvvvvvvvvvvvv\n" +
            "13-17 g: lhqgggcxlgcvgwgdg\n" +
            "6-13 x: kxxxxsxxxmxxxx\n" +
            "3-4 r: rrrqr\n" +
            "2-3 r: kvrsxjrmtvtr\n" +
            "1-2 h: jtbh\n" +
            "8-9 w: wwwwwdfckw\n" +
            "13-18 v: vvqwvvvnvvvvvvvsvv\n" +
            "6-14 t: mpfthffdnmtxmx\n" +
            "4-5 d: dddcsd\n" +
            "6-7 m: mlmmmnfmmh\n" +
            "5-7 x: xhxpkpqxqnx\n" +
            "9-11 v: vgvvqgvvwmkpfvvlv\n" +
            "15-18 l: jlxqvmjgrrnbhccpdl\n" +
            "2-9 k: kkkkznkkbf\n" +
            "14-15 w: wwwwwwwwwwwwwbwww\n" +
            "9-10 k: wkkvvmkkvgfkkk\n" +
            "10-15 g: bfggggggggggggg\n" +
            "7-8 x: xxxxxxxx\n" +
            "12-14 t: dmtmwtztltfsthtb\n" +
            "6-7 k: kkkkkwk\n" +
            "4-5 c: ccvsz\n" +
            "3-4 c: mclvcfjcqh\n" +
            "16-17 k: skkpknhxxsrqmcvkj\n" +
            "12-13 v: vvvvrfdfsdtvf\n" +
            "1-2 q: fpqp\n" +
            "7-8 b: bwbbbqbbb\n" +
            "5-6 h: hhhhhh\n" +
            "5-7 z: zzvzdzzxzwz\n" +
            "17-18 w: wwwwjhggnwbwwwwwzb\n" +
            "6-8 g: gggggtggg\n" +
            "4-8 n: lnnnzhbn\n" +
            "17-18 g: lggggggggcggglgggg\n" +
            "2-8 v: vbvvvvvkv\n" +
            "1-9 v: vvxvrvvtvvvvv\n" +
            "13-15 j: fhvxdngcrjdqxmnz\n" +
            "5-17 n: nnnnnnnznnnnnnwnnn\n" +
            "1-4 f: fnxdmjdsqbfffnjsnkf\n" +
            "3-8 q: dqqgbnbrpxqclq\n" +
            "4-6 b: xkpbbbk\n" +
            "11-12 l: llqllllllldjll\n" +
            "9-10 c: cwvlcdnmzr\n" +
            "6-8 l: zkjlllvlgvlnlblspm\n" +
            "4-9 b: lbbbbbbbbbwbbbw\n" +
            "9-12 g: gfgrggvgbggg\n" +
            "16-17 r: rrrrrrrrrrprrrrtc\n" +
            "2-16 r: mrbmrrxgrrbzrrmrrj\n" +
            "16-17 v: vnsvvczmjwfkvjvvvsrv\n" +
            "2-11 l: lglrllnlllqlll\n" +
            "2-8 t: sllgjrxkthl\n" +
            "3-7 d: ddldddk\n" +
            "8-13 c: ccckchmcdxccccccsf\n" +
            "8-9 t: cttbtztttfqdqh\n" +
            "4-5 b: tbbxh\n" +
            "12-17 w: wwwwwwwwlwwtwwwvtww\n" +
            "1-5 t: krfwxtzxcwphw\n" +
            "3-10 w: wwwwwwwwwwwww\n" +
            "1-2 n: nnjqqkspswql\n" +
            "9-13 w: wwwwwwwwfwwwwww\n" +
            "1-3 s: ssss\n" +
            "13-14 x: xfxxxxxtxxxxnx\n" +
            "4-5 x: xxxcj\n" +
            "5-15 k: kkkktkkkkkkkkkf\n" +
            "14-16 l: lrlzjxlllpqltlblvlll\n" +
            "5-6 t: ttttfct\n" +
            "11-14 z: zzzzzzrczdkzzz\n" +
            "6-8 f: ffffftfj\n" +
            "9-11 d: ljdngglsdvdsv\n" +
            "10-15 c: ccrqhcqzccnnjvcfcj\n" +
            "11-15 w: jwvwnccwwxzcwwww\n" +
            "9-10 s: ssssssssss\n" +
            "2-4 r: vzfmrr\n" +
            "5-8 l: blhlnlsqb\n" +
            "6-7 c: ccxxcfxldckpcc\n" +
            "2-4 j: czjkj\n" +
            "2-14 d: rlxksvpqsnhhpkds\n" +
            "16-19 k: kkkkkkkkkkkckvkjkkwp\n" +
            "3-9 j: kcjcbjjjjjjjjgljml\n" +
            "2-7 l: ljjzdll\n" +
            "4-8 r: fqnqjbsssqrrwrrrrr\n" +
            "5-15 t: xtnvhtttdsrhtttt\n" +
            "1-3 l: xlzl\n" +
            "6-10 g: ggggncchghgggghgg\n" +
            "10-11 m: msmmmmmcmgj\n" +
            "4-6 c: mcnprhmcfcclcl\n" +
            "12-13 s: ssssswssssstsss\n" +
            "13-14 m: mmmmmmmmmmmmmmmmm\n" +
            "9-11 p: kqvrdbpppcpgqh\n" +
            "6-7 q: qqqqqqq\n" +
            "9-10 b: bpbbnbbbkdbbsbblqrfb\n" +
            "12-13 b: bbbbbbbbbbstsb\n" +
            "8-11 g: ggbbfrsgdxhldnt\n" +
            "7-8 d: dddwddssdbd\n" +
            "6-7 b: bbbbkbfj\n" +
            "3-5 z: jtdklzthgz\n" +
            "5-6 l: hlnlllltmvhmlmq\n" +
            "3-6 q: qqpxqvqp\n" +
            "1-3 z: zskzmzzzhzzzhzvzrzzq\n" +
            "2-8 h: sskhzhlhkht\n" +
            "2-9 r: rltcgrrrrrrr\n" +
            "3-16 f: zrxffkfcvffffncffgff\n" +
            "1-2 r: rrcrhkns\n" +
            "14-17 b: bbbbbbbbbbbhjbgbdblb\n" +
            "4-15 c: cccccccwcckclccrcc\n" +
            "13-14 l: lkzlclbnlhlcnk\n" +
            "13-14 r: rrrrrrrrrrbrrr\n" +
            "4-5 k: cvhkkkbj\n" +
            "2-5 m: kmfnmzh\n" +
            "14-15 n: nnnnfnnnxnnnnnnndnnn\n" +
            "7-10 t: wttwkbhtpf\n" +
            "3-9 n: qjgzpnkpn\n" +
            "6-7 n: nhnnnzn\n" +
            "5-10 n: nngtndngcn\n" +
            "2-5 x: rdxnp\n" +
            "10-13 s: sssssssssxssssssss\n" +
            "6-8 n: mnjnnxnnvckn\n" +
            "2-10 p: gpxpglqwpppp\n" +
            "5-7 t: twtktdts\n" +
            "18-20 c: cccccccccccccccccccc\n" +
            "6-7 d: dddddddw\n" +
            "10-11 x: xxxjxxxxxvzxxxx\n" +
            "4-7 z: zrphzzlzhgfwd\n" +
            "4-8 l: lllnlllkl\n" +
            "2-7 q: kkwsgndmdrmsvfqj\n" +
            "4-7 m: mmnmjfmm\n" +
            "2-5 s: flhkzzs\n" +
            "12-15 x: xxxxxlxxxxxmxxs\n" +
            "9-11 v: vvvvvhvkbndjvx\n" +
            "1-9 n: kpqgbxnkx\n" +
            "5-10 f: ffdfrpfffffwfffff\n" +
            "1-3 f: jsvqkff\n" +
            "5-7 j: jsjjjfxl\n" +
            "8-14 z: zzznrzzzzzqzzz\n" +
            "1-12 d: dzlbdzhgmrdddc\n" +
            "12-13 k: kkkkkkkkkkkbk\n" +
            "7-8 m: pmmmmmmmm\n" +
            "1-6 s: bsssssvslx\n" +
            "6-8 d: dddgdgrtbfdm\n" +
            "11-14 k: gkplwxkmskwmdpm\n" +
            "6-10 x: xxxxxkxxlr\n" +
            "4-10 l: lllxlllllklllll\n" +
            "1-2 t: ttstmpksrrp\n" +
            "10-12 s: ssssdsssshscs\n" +
            "10-12 z: zzzzzzzzpwjszzzz\n" +
            "2-4 r: grrrctkzmw\n" +
            "1-2 l: fspl\n" +
            "3-5 k: kkkkk\n" +
            "5-12 b: bcbbbbjbbbbb\n" +
            "8-9 c: ccccccctcc\n" +
            "3-8 p: pmplmhpp\n" +
            "6-7 b: bjhfsbbx\n" +
            "16-19 d: dddddddddwdvddddkdg\n" +
            "5-6 j: sjrzcj\n" +
            "5-8 f: mfdffdgf\n" +
            "1-3 q: qcqqq\n" +
            "9-10 s: sbsssssspm\n" +
            "2-4 f: dffl\n" +
            "3-4 n: nnnn\n" +
            "4-10 t: wttthjpdmtlthttgwtkt\n" +
            "9-10 d: jpxdmbnddddd\n" +
            "10-19 q: sqhswtjrpqbxwjqzfqmr\n" +
            "2-6 w: swwzvgwbww\n" +
            "1-2 m: cfmmsl\n" +
            "9-14 w: pwdbjwwhbnpwllm\n" +
            "4-5 q: qqqqqqqqk\n" +
            "8-15 m: mmkdmwzkrvlmpmnmmmmf\n" +
            "17-18 q: qqqqqqqqqqqqgqqqnvq\n" +
            "3-6 g: gkkngh\n" +
            "1-8 g: gghdzwkg\n" +
            "3-11 j: vxdspqtvkpj\n" +
            "5-7 q: qqtqgpmqdq\n" +
            "6-8 d: bdmddddvd\n" +
            "5-6 w: zwwwwwvwxfw\n" +
            "2-11 n: bnplrmpvbpn\n" +
            "7-14 k: kkktbkkkkkkkkk\n" +
            "3-11 b: fmkqvvbztnxzqvjc\n" +
            "3-6 q: sscqqq\n" +
            "4-7 c: cfrrdrzbjmvpk\n" +
            "6-9 w: pwrtzwrww\n" +
            "2-5 v: vvcvv\n" +
            "2-4 f: ffmf\n" +
            "8-10 k: kkkkkkkpkd\n" +
            "6-7 v: mvjvvvv\n" +
            "8-11 c: vccvcckccfk\n" +
            "7-8 b: bbbbbbbsr\n" +
            "2-3 x: xxxmvx\n" +
            "6-7 l: llbllwsl\n" +
            "8-10 r: rrrrrbrrgrrrrnrb\n" +
            "12-16 g: ggggggzsggmwgggv\n" +
            "18-19 p: pprppppppppppppppppp\n" +
            "3-6 s: ssssssss\n" +
            "2-6 x: lwxkdx\n" +
            "2-3 n: xgbnf\n" +
            "2-4 p: dzrk\n" +
            "2-4 h: hlhpjhh\n" +
            "4-5 b: bmnbb\n" +
            "1-7 z: zczvzczsxmxpzznp\n" +
            "2-9 l: nlwxdwlblzl\n" +
            "1-4 r: xbtcqrfkv\n" +
            "13-16 k: skkkkkkvkkjkxrkfqk\n" +
            "9-14 b: bbbfcbwfjbbcbg\n" +
            "1-13 r: frrrrrrrrrrrfr\n" +
            "1-4 w: hwwxwnvvt\n" +
            "2-6 l: zzhlrx\n" +
            "3-8 v: vmzvggqtslnlqrj\n" +
            "15-16 s: dhssknsjztzssssssss\n" +
            "2-6 q: qqqqqqqq\n" +
            "2-3 t: mkktlt\n" +
            "7-17 b: bbbbbbbbbbbbbbbbdb\n" +
            "11-17 s: sssssszfssxssssskj\n" +
            "2-7 h: hnhkhshhhhhhhh\n" +
            "2-15 x: xzxjxnxxpxxkzxxxxj\n" +
            "15-16 p: pmcmpclzphppxplp\n" +
            "8-9 k: kkkkkkkdpkks\n" +
            "2-4 r: vrwt\n" +
            "8-12 r: qrrrhhwjrrrhrrr\n" +
            "3-4 j: vjjzq\n" +
            "8-10 q: qqqqqqqqgs\n" +
            "6-7 j: zjjjjjjj\n" +
            "1-11 m: mdgkdkmqzmmsrhxxmmj\n" +
            "1-7 x: pxxxrbq\n" +
            "3-4 z: zrhkzz\n" +
            "4-5 s: ssqlss\n" +
            "5-8 f: vtrfffffff\n" +
            "7-13 j: jjjjjjdjjjjjtj\n" +
            "1-7 n: dnnfxwz\n" +
            "2-11 n: nzgnqncnnnjg\n" +
            "4-5 x: xxxxx\n" +
            "5-7 v: rhbvvvvhvxvpz\n" +
            "10-11 z: zlbbddzlzwzv\n" +
            "10-13 v: vvvvvvvvvvvvvv\n" +
            "3-4 s: ssrs\n" +
            "11-12 m: mmmcmmfdmmsmmmmnm\n" +
            "5-7 s: sdstsssssrs\n" +
            "1-3 w: bwzw\n" +
            "3-4 h: hphq\n" +
            "7-16 q: qqqfqqdwksqlfcqjxq\n" +
            "6-7 x: kndcxfv\n" +
            "10-11 m: mmmmmmmmmmm\n" +
            "1-4 n: fvsvnfhgwcgcnp\n" +
            "13-14 s: ssssssssrssswrss\n" +
            "5-9 x: xmvkxwgrxrtwxmrxhxx\n" +
            "3-5 q: jdbvvxvdg\n" +
            "3-15 w: zlzcksssjbwcvgp\n" +
            "16-19 x: bxxxxxxxxxxxxxxxxxx\n" +
            "3-5 z: rzzhz\n" +
            "4-10 f: hpttvbtjmq\n" +
            "3-6 n: wsngjn\n" +
            "4-5 p: ppphg\n" +
            "10-12 c: bqlccfctmchqbchhcg\n" +
            "9-10 z: zzzzdzzzzhzzvz\n" +
            "7-9 w: nwgwcvdcxqqwmzq\n" +
            "14-19 x: pxtxxlbrxdpvspwmxxx\n" +
            "2-8 t: ssktwbft\n" +
            "8-9 j: jjjjjgjsjzjj\n" +
            "7-9 v: vvvvvvdvlvvwv\n" +
            "4-6 x: qxxkssx\n" +
            "11-13 g: ggggggggkgvgg\n" +
            "8-9 t: tttttvttjttwt\n" +
            "2-8 b: pfbbcsbwbbbb\n" +
            "8-16 r: mkrcrtsrrrrbxmprftvx\n" +
            "9-10 k: hvwlqvktkkb\n" +
            "1-6 w: wsbwwvjwwrwh\n" +
            "10-19 f: nfftfffrdhjffjsnffd\n" +
            "13-16 h: hhzghvhhhfhhhhhhhhh\n" +
            "14-16 x: kskxbwrwrvjxfvfg\n" +
            "1-4 k: rflk\n" +
            "6-7 b: bbbbbbgb\n" +
            "4-17 v: vvvvvvvvvvvvvvvvv\n" +
            "12-13 s: sdstmsspfwsssscqf\n" +
            "9-11 z: zzwzvmrzzczzzz\n" +
            "4-8 s: skslmgsqtszbswsssscs\n" +
            "4-12 h: bdshxnpgvwhktdwgdp\n" +
            "3-5 t: tltst\n" +
            "4-5 h: hhhhh\n" +
            "9-11 w: wwwwwnwxxwwwwwww\n" +
            "6-7 n: dcnngffnnzn\n" +
            "1-3 l: clflll\n" +
            "6-7 x: xxxzxxgx\n" +
            "6-7 n: nnnnnkgnnnnnn\n" +
            "1-6 m: mmmmmmmm\n" +
            "5-7 t: tktttpt\n" +
            "4-8 v: zpcvqvzvrvgttntrbl\n" +
            "6-7 d: dddrddd\n" +
            "3-5 k: jskdkswqjfftgkfr\n" +
            "5-6 f: ffffgrffn\n" +
            "6-8 l: lwlkllgl\n" +
            "10-13 p: ppppkpppppppd\n" +
            "4-5 d: hbjdd\n" +
            "9-15 r: rrxrrrrrrrrrrrrrgr\n" +
            "4-5 b: bbbbtbx\n" +
            "8-11 b: brbbtlvvlbdbbbqjsb\n" +
            "6-8 g: zgzqgwmg\n" +
            "4-9 r: qstrmxrtr\n" +
            "5-8 m: mbmjmmmmmr\n" +
            "5-7 v: tvvzqvgrvqvmvncshv\n" +
            "17-18 g: fgggggggggggggggwr\n" +
            "2-12 t: nttpgcjtkdjt\n" +
            "6-10 k: kkkkklkkkk\n" +
            "2-7 q: qqqmtgqq\n" +
            "3-6 n: npccknvnn\n" +
            "5-16 k: rtlhkbtdkmmntdbl\n" +
            "2-3 b: wwkb\n" +
            "7-17 q: qqqqqqqqqqqqqqqqqq\n" +
            "1-4 g: ltgc\n" +
            "2-6 l: lxlnln\n" +
            "13-15 q: qqqqqqqqqqqqqqxq\n" +
            "3-4 j: jvjj\n" +
            "5-15 c: cpmzlhcckwlnhwmwgzw\n" +
            "3-8 b: qvblmmchbcc\n" +
            "5-8 b: fqhdwtcxb\n" +
            "4-15 k: kkvkkkcwgkkbkkdkkkkn\n" +
            "11-12 f: fnffffffffffffff\n" +
            "9-10 t: tttttttpfvt\n" +
            "4-10 f: nfffpftfffffffnf\n" +
            "2-4 m: scgxnm\n" +
            "7-8 z: zzzzzzxhbz\n" +
            "6-9 z: vznwkzzzz\n" +
            "3-5 k: hkcdn\n" +
            "3-10 k: kkskkkkkkz\n" +
            "2-3 p: pbdf\n" +
            "1-4 m: mdhmm\n" +
            "6-10 b: lfbbwdbbtv\n" +
            "8-10 g: gggggggggggg\n" +
            "2-3 t: qgthtztbwtppb\n" +
            "15-17 n: nnnnnnnnnnnnnnbnjn\n" +
            "8-17 v: vvvvvvgkvfvvzvvvpv\n" +
            "4-5 f: vwffff\n" +
            "8-15 w: wwbvwwwwdwwkzwwwwwwf\n" +
            "7-13 n: srmzrmnvcgshljkchp\n" +
            "5-15 q: dqjvfqvpwqnmpwqzh\n" +
            "1-2 h: hhfs\n" +
            "2-6 h: jhqwhh\n" +
            "3-4 t: tthg\n" +
            "2-4 b: sxsqrrxkjb\n" +
            "6-8 q: qqqqqqqqqq\n" +
            "6-7 c: rqcxcclxccwqcgwq\n" +
            "4-5 v: vvmfv\n" +
            "6-7 m: mmmcmmmm\n" +
            "2-4 j: bqfj\n" +
            "2-12 k: kkkkvkkkkskkkkkk\n" +
            "5-9 q: xjtqqrnnkdplrnqq\n" +
            "1-6 k: bqkrfpkcrwwkk\n" +
            "1-4 r: mrblr\n" +
            "12-18 s: ssssbfdlqbbssplswpsl\n" +
            "8-9 b: bhbhhbbkbzbnbcbh\n" +
            "3-7 t: tsdtthx\n" +
            "12-15 f: xcmghffxtgfffjf\n" +
            "12-16 n: bxnnhnhnnzfnnnwrtgl\n" +
            "7-9 q: qqqcqmnqdq\n" +
            "2-3 m: rpbjgkxqtmjrzm\n" +
            "11-12 s: hssssssssshc\n" +
            "3-5 x: xxldx\n" +
            "3-4 k: kkkxt\n" +
            "7-9 k: wlgkqndkz\n" +
            "5-7 l: llmtllv\n" +
            "2-6 v: svzvfv\n" +
            "5-6 d: djdddvddd\n" +
            "5-6 k: mhkkkkkwvkkcfk\n" +
            "3-4 c: rjcc\n" +
            "4-8 t: ttttzfttc\n" +
            "10-11 g: ggzggngbzgg\n" +
            "14-16 w: qzqwdwbcwwwmllndzlsm\n" +
            "2-4 z: zzpz\n" +
            "12-13 g: gwxpwcbsvwgtthn\n" +
            "1-4 b: bbbbmzc\n" +
            "5-7 f: cnxlfdffmt\n" +
            "3-4 z: znsdz\n" +
            "10-13 c: mrckljhmrcmnc\n" +
            "2-9 m: dxmdhndrwpmpgc\n" +
            "7-16 z: zzzzzzzzzzzzzzzzz\n" +
            "1-3 j: jjjjjjjjjjjjjjjj\n" +
            "15-18 g: mmglvtgzggzgnggggg\n" +
            "4-10 c: cccncccccz\n" +
            "1-8 n: mnnnnnntn\n" +
            "10-13 l: llllllltzhlvvld\n" +
            "2-3 r: gnnd\n" +
            "3-7 v: vcnfzzbd\n" +
            "6-7 p: pprpctdp\n" +
            "5-8 g: gggggqgggg\n" +
            "1-13 f: wfffdfpbfjlfhb\n" +
            "3-8 j: dmjjkqwj\n" +
            "4-10 j: vfjhnswwwtzlfvmcdn\n" +
            "2-4 v: bnjd\n" +
            "4-7 w: btwwlfwkwzmzhhlsvs\n" +
            "14-15 g: gggggggggggggpgg\n" +
            "10-11 w: zwwwwwwpwgrww\n" +
            "2-3 b: dbbcgwqfzlhwcbs\n" +
            "1-9 f: qfpfvffffffmfxbcpf\n" +
            "9-10 t: tttbpttttmttcnt\n" +
            "2-3 l: lgll\n" +
            "8-9 s: vzgvjsnns\n" +
            "6-8 w: wwwdwsbtswrww\n" +
            "13-14 h: dhhhxhdjnvhrhrflhh\n" +
            "7-8 d: dddddvjd\n" +
            "14-15 l: lllqlllllllllnlxlh\n" +
            "12-13 d: ddddzdjdddhhkdd\n" +
            "9-14 p: pvtplhjvpzdvqjqvh\n" +
            "9-10 r: rjrrrrrtrrrr\n" +
            "6-8 g: gjjgfwgg\n" +
            "9-14 j: jjjjjjtjcjjjjhjjj\n" +
            "8-9 q: phxjqqnqq\n" +
            "5-6 k: lkkkkk\n" +
            "14-15 x: xxxxxgwxxxxxxtwxq\n" +
            "1-4 x: xqfxx\n" +
            "1-8 m: mmgmnmvm\n" +
            "2-3 n: hnwr\n" +
            "14-15 z: zzzzzzzzzzzzssz\n" +
            "2-6 p: pspppp\n" +
            "1-6 z: zzxzzx\n" +
            "9-18 z: zzzzzzgzzzzzzzzzzgz\n" +
            "6-11 z: wzhtdzzfxjz\n" +
            "3-4 v: vzvv\n" +
            "16-19 q: qqqqqqqlqqqqqxqqqqq\n" +
            "2-4 v: vvhvvvv\n" +
            "2-9 p: lpxppwppppgppspb\n" +
            "11-12 m: mmmmmmmmmmndm\n" +
            "8-9 v: vvvpjvvvpvv\n" +
            "16-19 k: kkkkkkkkkkkkkkfkkkk\n" +
            "9-10 z: zxlzfzczzzczrdn\n" +
            "12-18 p: ppppppppppbjpplpphp\n" +
            "1-3 p: pvpppx\n" +
            "1-2 x: vxlx\n" +
            "10-12 l: lllnlllllwlll\n" +
            "4-5 b: bphwg\n" +
            "7-10 c: gcjjpprxxjcwvk\n" +
            "6-9 l: llwqklmpxlszgzlvl\n" +
            "9-15 s: fsxsscswksvrmsh\n" +
            "15-16 q: lqxqqwqpqwptqqmg\n" +
            "10-13 r: xmpmqrdjkrzkpzc\n" +
            "3-5 c: kcbcclt\n" +
            "17-18 f: jffffsffffffffffbsff\n" +
            "1-3 t: vqcqdmmgc\n" +
            "1-2 n: qnnn\n" +
            "16-18 n: nnjzhnznnnxlrmmnsn\n" +
            "13-19 q: srxlcdznhbfxqtsqtsqx\n" +
            "2-7 m: vmmmnjmmmmz\n" +
            "6-7 v: vlvmjvg\n" +
            "7-15 k: xnpkbtzwgntptwkgmxm\n" +
            "15-19 g: wggggggggggsggkggxg\n" +
            "8-17 h: hhhhhhhwhhhhhhhhhh\n" +
            "2-5 w: kwwwww\n" +
            "4-12 k: kkkqkkkkkkkqkkkkkkk\n" +
            "7-11 d: hddcndsgddgz\n" +
            "2-7 t: tdzxnth\n" +
            "1-7 z: lzzcrvz\n" +
            "5-10 h: shvchmxxdh\n" +
            "12-13 f: kffwgtfsssfqnvff\n" +
            "1-9 b: mbbbbtxbrbbc\n" +
            "4-12 r: rnfvrprrrrzrrr\n" +
            "2-6 p: qzltppwqljg\n" +
            "2-4 w: hwdxwmmqphfkhthczx\n" +
            "3-4 r: rrwj\n" +
            "3-4 b: lbbbpldfj\n" +
            "4-12 g: gggggggggggggkv\n" +
            "4-5 r: rrqjtrrr\n" +
            "4-8 n: nnnrfhnfn\n" +
            "4-11 h: lrnxkwkbhgnhh\n" +
            "1-8 l: lvjlhbffl\n" +
            "6-10 g: ggtgghghghpfgg\n" +
            "1-2 s: szsss\n" +
            "3-6 s: dszxsdsssskssbs\n" +
            "11-14 x: xxxncxxxxxxxxq\n" +
            "5-10 m: mtmmmmmmmdmm\n" +
            "1-3 r: qrgr\n" +
            "2-7 m: gmhmmtd\n" +
            "1-3 c: cccswmjcmnm\n" +
            "2-9 x: qbcdsxxlx\n" +
            "6-7 s: nsswzssv\n" +
            "1-14 m: trmlzmsmgqmmmnfdsmtm\n" +
            "5-7 d: cdddzdtdd\n" +
            "3-4 k: tvczkxvvrw\n" +
            "2-8 s: slvmswvs\n" +
            "10-16 p: pppppppppgpptpptpp\n" +
            "2-11 l: jqxsjlvpzkgzjdmt\n" +
            "4-7 t: ttmtpttp\n" +
            "4-11 r: twbrxccwcrtffpnv\n" +
            "6-8 k: kkckkkkqkk\n" +
            "10-12 v: vvvvvvvvvvvv\n" +
            "4-6 k: gqzkkk\n" +
            "3-4 r: rrmxr\n" +
            "12-13 p: npgppsppppqnw\n" +
            "1-16 x: mxxxxxxxxxxxxxxv\n" +
            "5-6 l: llllll\n" +
            "1-4 k: bkkckkkkk\n" +
            "10-11 v: vkvtvkjltmlvtxlnlrsj\n" +
            "3-11 h: mzhrhlhhhhhwl\n" +
            "5-6 p: pppppp\n" +
            "1-17 m: mmmmmmmmmmmmmzmjmmmm\n" +
            "2-6 v: cvvcvfbgcvvvcq\n" +
            "4-7 n: nnsnnwj\n" +
            "2-3 k: xvkxkksvb\n" +
            "16-17 x: xxtxxxxxxxxxxxxxr\n" +
            "1-13 w: lwwwwwwwwwwwxw\n" +
            "3-14 d: ddjdddbddddddtdddd\n" +
            "4-10 g: jrxggnqmjg\n" +
            "1-3 b: bbfbbbbb\n" +
            "4-5 d: pdhdm\n" +
            "5-7 d: mvdsdnd\n" +
            "17-19 m: mlmmmmmmmmhmmmmmmmm\n" +
            "4-6 g: gtlgxggggsgc\n" +
            "6-7 m: mzvmhglmmmpmmxf\n" +
            "10-14 j: jrjjjxcjjtjjjhpljl\n" +
            "9-15 w: wwwwlwwwwwwwwwjwwdw\n" +
            "1-3 g: wtzgjgr\n" +
            "5-7 m: dmmmtmm\n" +
            "1-8 g: ggkdgpggg\n" +
            "5-6 x: xnjhmx\n" +
            "1-7 b: bbbbbbbfbbbb\n" +
            "3-11 n: mnnnngnnnvnnqnnvn\n" +
            "2-3 l: jglgdrczl\n" +
            "12-14 f: tffpffsmfffffg\n" +
            "10-13 d: mndmdwdxjdxpd\n" +
            "9-10 m: mlmmmmmmzvxm\n" +
            "6-8 l: ptpjwltl\n" +
            "7-8 r: rrdrprlqrr\n" +
            "8-9 n: nnnnnnnrc\n" +
            "6-7 p: ppppphn\n" +
            "4-8 t: smtptgwtmlttw\n" +
            "4-10 j: jsjjjjjjjj\n" +
            "15-18 k: kkhwkkkkkkkkkkkkkk\n" +
            "1-2 s: sksxb\n" +
            "2-10 g: sggchblktg\n" +
            "8-12 r: rrrrrrrrbwrr\n" +
            "13-14 v: vvvvvvvvzvcvvvvv\n" +
            "3-4 p: kppp\n" +
            "4-14 m: mmmsmmmmmmmmmzm\n" +
            "5-6 n: kndmnnnnpnznjqb\n" +
            "3-10 d: xlddcdbdlddpqdkdl\n" +
            "17-18 n: tnmcvdcznnnfnznldt\n" +
            "6-11 g: wgbgzgggggg\n" +
            "16-18 z: zzzzzttzzzzzzzzkzq\n" +
            "11-13 x: pxxlgmtvbjrlb\n" +
            "2-13 p: bmphpwxpsmmthppprdk\n" +
            "14-16 r: rmrrrrrdmrrrrztrjr\n" +
            "1-5 x: xdxxx\n" +
            "1-3 d: dgdddfzddfd\n" +
            "1-9 m: ddfmgwfgf\n" +
            "7-11 x: xwnqqtxdmns\n" +
            "5-6 v: ffvvvv\n" +
            "3-15 g: dggggggzggggggb\n" +
            "10-13 p: pptpppkdpwcngppf\n" +
            "11-12 x: xxngxbxxdxxxxnzxbxx\n" +
            "3-4 n: nxqc\n" +
            "1-2 x: dvxxx\n" +
            "4-5 h: zhvhh\n" +
            "3-5 j: jqpjj\n" +
            "2-7 f: ffffffpfz\n" +
            "8-10 k: kkkkkkkkkk\n" +
            "5-12 x: xxtxxxxxxxxxxx\n" +
            "12-14 c: cccccccccccccc\n" +
            "8-9 s: vhlssssws\n" +
            "1-4 k: dqkk\n" +
            "4-10 r: rrbrrrrrrdrr\n" +
            "1-3 r: hqljfr\n" +
            "8-12 c: qcccccszgjgcccddccw\n" +
            "6-14 m: mmmmmxmmpmmqmcmmdm\n" +
            "5-6 r: mwrrdtm\n" +
            "1-5 t: rdjtts\n" +
            "6-14 c: gpcbczvfbcbcckblzc\n" +
            "5-6 w: wxwwww\n" +
            "3-4 p: rjppp\n" +
            "10-13 t: ttttttctdtgtttts\n" +
            "3-14 c: cvlcpqscwgzgxzxvkmh\n" +
            "3-7 h: kxqfwfddhllhj\n" +
            "10-18 r: mdqrrmrdxkkvxftrrr\n" +
            "13-14 m: cmmmcgmmmmhvmm\n" +
            "2-7 h: khvhhjhhjbv\n" +
            "5-9 r: rrrzgrrrlr\n" +
            "1-8 c: gccccccsccc\n" +
            "15-17 v: vvvvvvvvvvvvvvdvn\n" +
            "9-13 v: vbvdgpvjvhvhwxv\n" +
            "6-9 z: zzxbqznzqjzh\n" +
            "3-6 r: rrrrrrrrrrrrrrrrrrrr\n" +
            "3-4 x: nxxxxst\n" +
            "7-10 q: qqqqqqfqqf\n" +
            "9-10 j: jjbjdjqcqw\n" +
            "9-13 z: dhzzzzzzzzzwxkzzzzjk\n" +
            "3-9 q: pqxgqqcqqjql\n" +
            "10-11 h: ljhgjwhzdrhhhh\n" +
            "18-19 v: vvvvvvvvvvvvvvvvvvvv\n" +
            "10-11 l: vgxrhvtfblwl\n" +
            "2-3 v: rvvvvpj\n" +
            "8-9 c: smchcscccdmf\n" +
            "2-3 n: nqmnn\n" +
            "15-17 x: xxxxxxxxxxxxxxqxrxk\n" +
            "11-14 j: jjjjjjjjjjljjvj\n" +
            "7-9 z: zvzzmzjkfbvzzczczlzm\n" +
            "2-6 z: zzzjzjzzmfzk\n" +
            "9-11 m: mvcmmbmlzrmmz\n" +
            "6-7 r: rrrrrrr\n" +
            "3-6 c: jtcfscccvvf\n" +
            "2-5 s: cssbntxggkwvwnchn\n" +
            "8-10 x: xxsxjzxqxx\n" +
            "6-7 n: ndnnnbg\n" +
            "9-16 j: jgzxxsmljbhbttqjw\n" +
            "3-4 k: gjsk\n" +
            "9-10 q: qqcrqqqpqq\n" +
            "2-4 t: thtt\n" +
            "3-4 w: wrfxww\n" +
            "9-14 v: vvsvvkqgzvmvvvvvlvvv\n" +
            "9-15 m: mmmmkmxdmdmmhmmwjw\n" +
            "3-9 b: bbbbwcwbb\n" +
            "3-6 c: ctdccs\n" +
            "7-8 k: kkqrkkkk\n" +
            "5-7 l: llmllcqjljlh\n" +
            "5-7 w: wnzbwgw\n" +
            "15-17 f: fcffffffffffffffpf\n" +
            "1-2 t: tttft\n" +
            "1-7 n: zctqhnxvbn\n" +
            "3-8 z: hdpqzzzlzsw\n" +
            "3-15 l: llslllllllllllml\n" +
            "8-19 w: rwtbwrwjwtwxcclthdw\n" +
            "4-5 g: zggggg\n" +
            "5-14 v: vvvvhvvvvvvvmlvv\n" +
            "1-7 l: mlgxllpgl\n" +
            "2-12 b: mvwbfjcddqjb\n" +
            "1-3 m: qmzm\n" +
            "2-3 r: rrrrrffr\n" +
            "1-7 x: xxsgxxv\n" +
            "8-10 d: tdrrqdzcdddddxddl\n" +
            "2-4 n: crnnfdcnnnzn\n" +
            "3-4 n: nnnz\n" +
            "9-10 z: zzzzqfzzzzz\n" +
            "10-16 n: nnnhmnnznsnntnnc\n" +
            "9-16 s: vssssbsscssssssjss\n" +
            "9-13 w: wwkwwwqqwvwwww\n" +
            "4-5 d: hkdhwddtdkqwvl\n" +
            "3-4 l: llll\n" +
            "4-5 f: ffzffftld\n" +
            "7-9 d: ddddddddgd\n" +
            "6-7 t: ttthptttqxlfddstsq\n" +
            "5-16 c: clhwccvlnmttjqcc\n" +
            "4-5 k: pkkkk\n" +
            "7-11 m: xwmmmmchmmt\n" +
            "16-17 n: nnnnnnnnnnhnnnnrm\n" +
            "5-8 b: bbbbbbbbb\n" +
            "1-4 s: jsss\n" +
            "3-4 h: rhhhtjwfvdhz\n" +
            "9-10 r: rrrprlrwrrw\n" +
            "1-6 n: nnnnnkn\n" +
            "18-19 p: ppppppppppppppppppp\n" +
            "4-5 l: ljlrcl\n" +
            "3-7 m: mmmmmjmdmtm\n" +
            "12-13 b: bbbbbbbbbbbvf\n" +
            "6-11 g: hcghdwfpcqk\n" +
            "4-6 q: krpfvw\n" +
            "10-13 j: jsjkvjjjjjzjjfj\n" +
            "5-6 n: lcnnnnzndqkfnsq\n" +
            "2-4 j: nvdj\n" +
            "2-5 p: hppnpmpq\n" +
            "2-4 w: wnwbw\n" +
            "2-7 f: fwfxfmfszmcxf\n" +
            "6-8 d: dqrdbsnjds\n" +
            "1-3 f: ffffffmff\n" +
            "5-8 s: lnbwqnkxws\n" +
            "10-12 n: nnnnnnjnnnnnjcn\n" +
            "9-12 c: pccvnbccxrncrcclccc\n" +
            "14-18 s: ssssssssslsssstsssss\n" +
            "3-6 l: lldllczl\n" +
            "6-11 g: gggggwgggghg\n" +
            "11-12 h: chhhmjhzhqfh\n" +
            "5-6 n: qhnvcw\n" +
            "6-7 k: nckkkkmnkkkzkkk\n" +
            "6-8 d: wddgbdpdzdqxrwddjlz\n" +
            "1-3 h: qghp\n" +
            "3-5 j: mnjjjxjkgnrdzjbtdr\n" +
            "1-9 g: gfgcgggxgjggggggf\n" +
            "8-20 b: vptprmjbwwtnbhwjtnjb\n" +
            "7-8 j: jjjjjjjj\n" +
            "3-4 t: tqtt\n" +
            "5-10 f: fffzbxxszjjvjfhn\n" +
            "3-4 t: tttttttbtt\n" +
            "4-7 p: wjrgpnj\n" +
            "1-9 g: pgzllxgfg\n" +
            "14-15 c: cccccccccccccqm\n" +
            "11-12 b: btmcbzbnzcbbxr\n" +
            "5-6 h: hhhhhhh\n" +
            "1-6 s: nssmsssss\n" +
            "11-12 d: ddddddbddthfdddd\n" +
            "11-13 j: jtjjjjjjpjjjjwfjj\n" +
            "2-4 j: gjjj\n" +
            "3-9 v: vvgvvvvvrv\n" +
            "1-2 l: tqjjljxcsl\n" +
            "5-6 q: nqqqqr\n" +
            "12-16 h: hkhhhhhjhhhhqxhhhhhh\n" +
            "2-6 p: lpppkpbpzg\n" +
            "2-7 v: vzvvvvfv\n" +
            "13-16 g: ggggggggggggwggb\n" +
            "3-14 j: ghsjjcgmkwsdchlslpf\n" +
            "1-3 s: ssplw\n" +
            "7-8 x: xxxnxxxxxxx\n" +
            "3-4 h: zghhvtwtmlplvxxhsbf\n" +
            "4-5 g: sqgsnf\n" +
            "14-17 z: zzzzzzzzzzzzzwczc\n" +
            "1-2 z: cpzzzzk\n" +
            "16-17 s: ssssssssssfsqssss\n" +
            "3-9 j: jvjjfjdjjjjjh\n" +
            "1-6 v: vtvrvvj\n" +
            "4-8 c: clzcccccccf\n" +
            "4-5 d: dwldw\n" +
            "2-4 l: lwlrllllllll\n" +
            "6-11 s: zxgcsdxkrcns\n" +
            "14-17 r: vrhvhrprrfrsrrrrr\n" +
            "3-6 p: mrcztppnl\n" +
            "4-6 w: wwwwwwwwww\n" +
            "1-6 w: zwjccrqpwmnthz\n" +
            "2-7 t: mnjntdcq\n" +
            "1-5 b: bbjbbbbb\n" +
            "10-11 w: wwwwwtwwwwww\n" +
            "4-6 d: dddxdfd\n" +
            "2-4 f: fjfff\n" +
            "13-15 b: vbbbbbbbbbbbbbb\n" +
            "8-9 n: ncbnnnnnn\n" +
            "2-6 d: hdfphnnmbbdt\n" +
            "1-4 f: wffz\n" +
            "7-15 f: ffsffffffffffvzff\n" +
            "8-10 c: zchrckkcqcr\n" +
            "2-6 h: thvbvh").split("\n"));


    private static int part = 1;

    public static void main(String[] args) {
        part1();
        part2();
    }

    private static void part1() {
        part = 1;
        getValidPasswordCount(passwordWithRules);
    }

    private static void part2(){
        part = 2;
        getValidPasswordCount(passwordWithRules);
    }


    private static void getValidPasswordCount(List<String> passwordWithRules) {
        int valid = 0;
        for (String passwordRule : passwordWithRules) {
            if (validPassword(passwordRule)) {
                valid++;
            }
        }

        System.out.println(valid);
    }

    private static boolean validPassword(String passwordRule) {
        String[] split = passwordRule.split(":");
        String rule = split[0];
        String[] ruleSplit = rule.split(" ");
        String range = ruleSplit[0];
        String[] rangeSplit = range.split("-");
        int firstNum = Integer.parseInt(rangeSplit[0]);
        int secondNum = Integer.parseInt(rangeSplit[1]);
        char toMatch = ruleSplit[1].charAt(0);

        String password = split[1].trim();
        if (part == 1) {
            return validatePassword(password, toMatch, firstNum, secondNum);
        } else if (part == 2){
            return validatePassword2(password, toMatch, firstNum, secondNum);
        }
        return false;
    }

    private static boolean validatePassword(String password, char toMatch, int min, int max) {
        int occurrences = 0;
        for (int i = 0; i < password.length(); i++) {
            if (password.charAt(i) == toMatch) {
                if (++occurrences > max) {
                    return false;
                }
            }
        }

        return occurrences >= min;
    }

    private static boolean validatePassword2(String password, char toMatch, int pos1, int pos2) {
        return password.charAt(pos1-1) == toMatch ^ password.charAt(pos2-1) == toMatch;
    }

}
